export enum Enums {
  AED = 47,
  AMD = 56,
  ARS = 55,
  AUD = 10,
  AZN = 53,
  BDT = 33,
  BGN = 54,
  BND = 30,
  BRL = 35,
  CAD = 14,
  CHF = 12,
  CLP = 62,
  CNY = 1,
  COP = 20,
  CZK = 24,
  DKK = 18,
  EGP = 43,
  EUR = 34,
  GBP = 11,
  HKD = 41,
  HRK = 23,
  HUF = 25,
  IDR = 8,
  IDR2 = 57,
  IDR3 = 221,
  INR = 16,
  JPY = 6,
  KES = 50,
  KHR = 31,
  KHR2 = 64,
  KRW = 3,
  KRW2 = 58,
  KSH = 46,
  LAK = 48,
  LAK2 = 63,
  LKR = 65,
  MAD = 42,
  MMK = 21,
  MMK2 = 59,
  MNT = 68,
  MXN = 13,
  MYR = 4,
  NGN = 49,
  NOK = 19,
  NPR = 45,
  NTD = 61,
  NZD = 28,
  PEN = 67,
  PHP = 36,
  PKR = 40,
  PLN = 22,
  RON = 17,
  RUB = 15,
  SAR = 52,
  SEK = 27,
  SGD = 5,
  THB = 7,
  TND = 37,
  TRY = 29,
  TWD = 38,
  UAH = 39,
  UGX = 51,
  USD = 2,
  USDT = 32,
  VES = 66,
  VND = 9,
  VND2 = 60,
  VND3 = 219,
  ZAR = 26,
  ZMW = 44,
  AOA = 73,
  COP2 = 86,
  CRC = 82,
  DZD = 69,
  ETB = 70,
  FRF = 71,
  GC = 87,
  GTQ = 83,
  HNL = 84,
  IRR = 74,
  IRR2 = 75,
  LBP = 76,
  LBP2 = 77,
  PTI = 80,
  PTV = 81,
  PYG = 72,
  SC = 85,
  UZS = 78,
  UZS2 = 79,
  AFN = 88,
  ALL = 89,
  ANG = 90,
  AWG = 91,
  BAM = 92,
  BBD = 93,
  BDT2 = 94,
  BHD = 95,
  BIF = 96,
  BMD = 97,
  BOB = 98,
  BRL2 = 99,
  BSD = 100,
  BTC = 101,
  BTN = 102,
  BWP = 103,
  BYN = 104,
  BZD = 105,
  CDF = 106,
  CDF2 = 107,
  CLF = 108,
  CNY2 = 109,
  CSD = 110,
  CUC = 111,
  CUP = 112,
  CVE = 113,
  DJF = 114,
  DOGE = 115,
  DOP = 116,
  ERN = 117,
  ETH = 118,
  EUR2 = 119,
  FJD = 120,
  FKP = 121,
  FTN = 122,
  GEL = 123,
  GGP = 124,
  GHS = 125,
  GIP = 126,
  GMD = 127,
  GNF = 128,
  GYD = 129,
  HKD2 = 130,
  HTG = 131,
  ILS = 132,
  IMP = 133,
  INR2 = 134,
  IQD = 135,
  ISK = 136,
  JEP = 137,
  JMD = 138,
  JOD = 139,
  JPY2 = 140,
  KGS = 141,
  KWD = 142,
  KZT = 143,
  LRD = 144,
  LSL = 145,
  LTC = 146,
  LYD = 147,
  MAD2 = 148,
  MBTC = 149,
  MDL = 150,
  METH = 151,
  MGA = 152,
  MKD = 153,
  MMK3 = 154,
  MNT2 = 155,
  MOP = 156,
  MRU = 157,
  MVR = 158,
  MWK = 159,
  MXBT = 160,
  MXN2 = 161,
  MYR2 = 162,
  MZN = 163,
  NAD = 164,
  NGN2 = 165,
  NIO = 166,
  NOT = 167,
  NPR2 = 168,
  OMR = 169,
  PAB = 170,
  PGK = 171,
  PHP2 = 172,
  PKR2 = 173,
  PYG2 = 174,
  QAR = 175,
  RSD = 176,
  RWF = 177,
  SBD = 178,
  SCR = 179,
  SDG = 180,
  SGD2 = 181,
  SHP = 182,
  SLL = 183,
  SOS = 184,
  SRD = 185,
  SSP = 186,
  STD = 187,
  STN = 188,
  SVC = 189,
  SYP = 190,
  SZL = 191,
  THB2 = 192,
  TJS = 193,
  TMT = 194,
  TON = 195,
  TOP = 196,
  TRY2 = 197,
  TTD = 198,
  TWD2 = 199,
  TWD5 = 222,
  TWD7 = 220,
  TZS = 200,
  TZS2 = 201,
  UBTC = 202,
  UGX2 = 203,
  USD2 = 204,
  USDC = 205,
  USDT2 = 206,
  UXBT = 207,
  UYU = 208,
  VUV = 209,
  WST = 210,
  XAF = 211,
  XCD = 212,
  XDR = 213,
  XOF = 214,
  XPF = 215,
  YER = 216,
  ZWL = 217,
  MYR3 = 218
}

export const I18nKeys: Record<Enums, string> = {
  [Enums.AED]: "currency.AED",
  [Enums.AMD]: "currency.AMD",
  [Enums.ARS]: "currency.ARS",
  [Enums.AUD]: "currency.AUD",
  [Enums.AZN]: "currency.AZN",
  [Enums.BDT]: "currency.BDT",
  [Enums.BGN]: "currency.BGN",
  [Enums.BND]: "currency.BND",
  [Enums.BRL]: "currency.BRL",
  [Enums.CAD]: "currency.CAD",
  [Enums.CHF]: "currency.CHF",
  [Enums.CLP]: "currency.CLP",
  [Enums.CNY]: "currency.CNY",
  [Enums.COP]: "currency.COP",
  [Enums.CZK]: "currency.CZK",
  [Enums.DKK]: "currency.DKK",
  [Enums.EGP]: "currency.EGP",
  [Enums.EUR]: "currency.EUR",
  [Enums.GBP]: "currency.GBP",
  [Enums.HKD]: "currency.HKD",
  [Enums.HRK]: "currency.HRK",
  [Enums.HUF]: "currency.HUF",
  [Enums.IDR]: "currency.IDR",
  [Enums.IDR2]: "currency.IDR2",
  [Enums.IDR3]: "currency.IDR3",
  [Enums.INR]: "currency.INR",
  [Enums.JPY]: "currency.JPY",
  [Enums.KES]: "currency.KES",
  [Enums.KHR]: "currency.KHR",
  [Enums.KHR2]: "currency.KHR2",
  [Enums.KRW]: "currency.KRW",
  [Enums.KRW2]: "currency.KRW2",
  [Enums.KSH]: "currency.KSH",
  [Enums.LAK]: "currency.LAK",
  [Enums.LAK2]: "currency.LAK2",
  [Enums.LKR]: "currency.LKR",
  [Enums.MAD]: "currency.MAD",
  [Enums.MMK]: "currency.MMK",
  [Enums.MMK2]: "currency.MMK2",
  [Enums.MNT]: "currency.MNT",
  [Enums.MXN]: "currency.MXN",
  [Enums.MYR]: "currency.MYR",
  [Enums.NGN]: "currency.NGN",
  [Enums.NOK]: "currency.NOK",
  [Enums.NPR]: "currency.NPR",
  [Enums.NTD]: "currency.NTD",
  [Enums.NZD]: "currency.NZD",
  [Enums.PEN]: "currency.PEN",
  [Enums.PHP]: "currency.PHP",
  [Enums.PKR]: "currency.PKR",
  [Enums.PLN]: "currency.PLN",
  [Enums.RON]: "currency.RON",
  [Enums.RUB]: "currency.RUB",
  [Enums.SAR]: "currency.SAR",
  [Enums.SEK]: "currency.SEK",
  [Enums.SGD]: "currency.SGD",
  [Enums.THB]: "currency.THB",
  [Enums.TND]: "currency.TND",
  [Enums.TRY]: "currency.TRY",
  [Enums.TWD]: "currency.TWD",
  [Enums.UAH]: "currency.UAH",
  [Enums.UGX]: "currency.UGX",
  [Enums.USD]: "currency.USD",
  [Enums.USDT]: "currency.USDT",
  [Enums.VES]: "currency.VES",
  [Enums.VND]: "currency.VND",
  [Enums.VND2]: "currency.VND2",
  [Enums.ZAR]: "currency.ZAR",
  [Enums.ZMW]: "currency.ZMW",
  [Enums.AOA]: "currency.AOA",
  [Enums.COP2]: "currency.COP2",
  [Enums.CRC]: "currency.CRC",
  [Enums.DZD]: "currency.DZD",
  [Enums.ETB]: "currency.ETB",
  [Enums.FRF]: "currency.FRF",
  [Enums.GC]: "currency.GC",
  [Enums.GTQ]: "currency.GTQ",
  [Enums.HNL]: "currency.HNL",
  [Enums.IRR]: "currency.IRR",
  [Enums.IRR2]: "currency.IRR2",
  [Enums.LBP]: "currency.LBP",
  [Enums.LBP2]: "currency.LBP2",
  [Enums.PTI]: "currency.PTI",
  [Enums.PTV]: "currency.PTV",
  [Enums.PYG]: "currency.PYG",
  [Enums.SC]: "currency.SC",
  [Enums.UZS]: "currency.UZS",
  [Enums.UZS2]: "currency.UZS2",
  [Enums.AFN]: "currency.AFN",
  [Enums.ALL]: "currency.ALL",
  [Enums.ANG]: "currency.ANG",
  [Enums.AWG]: "currency.AWG",
  [Enums.BAM]: "currency.BAM",
  [Enums.BBD]: "currency.BBD",
  [Enums.BDT2]: "currency.BDT2",
  [Enums.BHD]: "currency.BHD",
  [Enums.BIF]: "currency.BIF",
  [Enums.BMD]: "currency.BMD",
  [Enums.BOB]: "currency.BOB",
  [Enums.BRL2]: "currency.BRL2",
  [Enums.BSD]: "currency.BSD",
  [Enums.BTC]: "currency.BTC",
  [Enums.BTN]: "currency.BTN",
  [Enums.BWP]: "currency.BWP",
  [Enums.BYN]: "currency.BYN",
  [Enums.BZD]: "currency.BZD",
  [Enums.CDF]: "currency.CDF",
  [Enums.CDF2]: "currency.CDF2",
  [Enums.CLF]: "currency.CLF",
  [Enums.CNY2]: "currency.CNY2",
  [Enums.CSD]: "currency.CSD",
  [Enums.CUC]: "currency.CUC",
  [Enums.CUP]: "currency.CUP",
  [Enums.CVE]: "currency.CVE",
  [Enums.DJF]: "currency.DJF",
  [Enums.DOGE]: "currency.DOGE",
  [Enums.DOP]: "currency.DOP",
  [Enums.ERN]: "currency.ERN",
  [Enums.ETH]: "currency.ETH",
  [Enums.EUR2]: "currency.EUR2",
  [Enums.FJD]: "currency.FJD",
  [Enums.FKP]: "currency.FKP",
  [Enums.FTN]: "currency.FTN",
  [Enums.GEL]: "currency.GEL",
  [Enums.GGP]: "currency.GGP",
  [Enums.GHS]: "currency.GHS",
  [Enums.GIP]: "currency.GIP",
  [Enums.GMD]: "currency.GMD",
  [Enums.GNF]: "currency.GNF",
  [Enums.GYD]: "currency.GYD",
  [Enums.HKD2]: "currency.HKD2",
  [Enums.HTG]: "currency.HTG",
  [Enums.ILS]: "currency.ILS",
  [Enums.IMP]: "currency.IMP",
  [Enums.INR2]: "currency.INR2",
  [Enums.IQD]: "currency.IQD",
  [Enums.ISK]: "currency.ISK",
  [Enums.JEP]: "currency.JEP",
  [Enums.JMD]: "currency.JMD",
  [Enums.JOD]: "currency.JOD",
  [Enums.JPY2]: "currency.JPY2",
  [Enums.KGS]: "currency.KGS",
  [Enums.KWD]: "currency.KWD",
  [Enums.KZT]: "currency.KZT",
  [Enums.LRD]: "currency.LRD",
  [Enums.LSL]: "currency.LSL",
  [Enums.LTC]: "currency.LTC",
  [Enums.LYD]: "currency.LYD",
  [Enums.MAD2]: "currency.MAD2",
  [Enums.MBTC]: "currency.MBTC",
  [Enums.MDL]: "currency.MDL",
  [Enums.METH]: "currency.METH",
  [Enums.MGA]: "currency.MGA",
  [Enums.MKD]: "currency.MKD",
  [Enums.MMK3]: "currency.MMK3",
  [Enums.MNT2]: "currency.MNT2",
  [Enums.MOP]: "currency.MOP",
  [Enums.MRU]: "currency.MRU",
  [Enums.MVR]: "currency.MVR",
  [Enums.MWK]: "currency.MWK",
  [Enums.MXBT]: "currency.MXBT",
  [Enums.MXN2]: "currency.MXN2",
  [Enums.MYR2]: "currency.MYR2",
  [Enums.MZN]: "currency.MZN",
  [Enums.NAD]: "currency.NAD",
  [Enums.NGN2]: "currency.NGN2",
  [Enums.NIO]: "currency.NIO",
  [Enums.NOT]: "currency.NOT",
  [Enums.NPR2]: "currency.NPR2",
  [Enums.OMR]: "currency.OMR",
  [Enums.PAB]: "currency.PAB",
  [Enums.PGK]: "currency.PGK",
  [Enums.PHP2]: "currency.PHP2",
  [Enums.PKR2]: "currency.PKR2",
  [Enums.PYG2]: "currency.PYG2",
  [Enums.QAR]: "currency.QAR",
  [Enums.RSD]: "currency.RSD",
  [Enums.RWF]: "currency.RWF",
  [Enums.SBD]: "currency.SBD",
  [Enums.SCR]: "currency.SCR",
  [Enums.SDG]: "currency.SDG",
  [Enums.SGD2]: "currency.SGD2",
  [Enums.SHP]: "currency.SHP",
  [Enums.SLL]: "currency.SLL",
  [Enums.SOS]: "currency.SOS",
  [Enums.SRD]: "currency.SRD",
  [Enums.SSP]: "currency.SSP",
  [Enums.STD]: "currency.STD",
  [Enums.STN]: "currency.STN",
  [Enums.SVC]: "currency.SVC",
  [Enums.SYP]: "currency.SYP",
  [Enums.SZL]: "currency.SZL",
  [Enums.THB2]: "currency.THB2",
  [Enums.TJS]: "currency.TJS",
  [Enums.TMT]: "currency.TMT",
  [Enums.TON]: "currency.TON",
  [Enums.TOP]: "currency.TOP",
  [Enums.TRY2]: "currency.TRY2",
  [Enums.TTD]: "currency.TTD",
  [Enums.TWD2]: "currency.TWD2",
  [Enums.TWD5]: "currency.TWD5",
  [Enums.TWD7]: "currency.TWD7",
  [Enums.TZS]: "currency.TZS",
  [Enums.TZS2]: "currency.TZS2",
  [Enums.UBTC]: "currency.UBTC",
  [Enums.UGX2]: "currency.UGX2",
  [Enums.USD2]: "currency.USD2",
  [Enums.USDC]: "currency.USDC",
  [Enums.USDT2]: "currency.USDT2",
  [Enums.UXBT]: "currency.UXBT",
  [Enums.UYU]: "currency.UYU",
  [Enums.VUV]: "currency.VUV",
  [Enums.WST]: "currency.WST",
  [Enums.XAF]: "currency.XAF",
  [Enums.XCD]: "currency.XCD",
  [Enums.XDR]: "currency.XDR",
  [Enums.XOF]: "currency.XOF",
  [Enums.XPF]: "currency.XPF",
  [Enums.YER]: "currency.YER",
  [Enums.ZWL]: "currency.ZWL",
  [Enums.MYR3]: "currency.MYR3",
  [Enums.VND3]: "currency.VND3"
}
