export const handleFullOrderDetailPageInputClick = "handleFullOrderDetailPageInputClick";
export const handleFullOrderDetailPageUploadClick = "handleFullOrderDetailPageUploadClick";
export const handleFullOrderDetailPageConfirmClick = "handleFullOrderDetailPageConfirmClick";