export const handlepopPageRegitsterSuccessModalPlayInBrowserBtnClick =
  'handlepopPageRegitsterSuccessModalPlayInBrowserBtnClick';

export const handlepopPageRegitsterSuccessModalDownLoadAppBtnClick =
  'handlepopPageRegitsterSuccessModalDownLoadAppBtnClick';

export const handlepopPageRegitsterSuccessModalCloseIconClick =
  'handlepopPageRegitsterSuccessModalCloseIconClick';

export const handlepopPageLecutreModalCloseIconClick =
  'handlepopPageLecutreModalCloseIconClick';
