source 'git@github.com/CocoaPods/Specs.git'
platform :ios, '9.0'


target 'bbg' do

    pod 'WeexSDK', '0.30.0'
    pod 'WeexPluginLoader'
    pod 'SDWebImage', '3.8.2'
    pod 'SocketRocket', '0.4.2'
    pod 'WXDevtool', '0.24.0', :configurations => ['Debug']
    pod 'ZipArchive', '1.4.0'

    pod 'WeexImageCropPicker'
    pod 'SAMKeychain'

#jpush

    pod 'JPush', '4.8.0'
    pod 'JPushWeexPlugin', '0.0.3'


#openinstall
    pod 'libOpenInstallSDK'

end
