import { computed } from "vue"

export enum Enums {
  // Countries
  PHILIPPINES = "philippines",
  AFGHANISTAN = "afghanistan",
  ALBANIA = "albania",
  ALGERIA = "algeria",
  ANDORRA = "andorra",
  ANGOLA = "angola",
  ANTIGUA_AND_BARBUDA = "antigua_and_barbuda",
  ARGENTINA = "argentina",
  ARMENIA = "armenia",
  AUSTRALIA = "australia",
  AUSTRIA = "austria",
  AZERBAIJAN = "azerbaijan",
  BAHAMAS = "bahamas",
  BAHRAIN = "bahrain",
  BANGLADESH = "bangladesh",
  BARBADOS = "barbados",
  BELARUS = "belarus",
  BELGIUM = "belgium",
  BELIZE = "belize",
  BENIN = "benin",
  BHUTAN = "bhutan",
  BOLIVIA = "bolivia",
  BOSNIA_AND_HERZEGOVINA = "bosnia_and_herzegovina",
  BOTSWANA = "botswana",
  BRAZIL = "brazil",
  BRUNEI = "brunei",
  BULGARIA = "bulgaria",
  BURKINA_FASO = "burkina_faso",
  BURUNDI = "burundi",
  CAMBODIA = "cambodia",
  CAMEROON = "cameroon",
  CANADA = "canada",
  CAPE_VERDE = "cape_verde",
  CENTRAL_AFRICAN_REPUBLIC = "central_african_republic",
  CHAD = "chad",
  CHILE = "chile",
  CHINA = "china",
  COLOMBIA = "colombia",
  COMOROS = "comoros",
  CONGO = "congo",
  COSTA_RICA = "costa_rica",
  CROATIA = "croatia",
  CUBA = "cuba",
  CYPRUS = "cyprus",
  CZECH_REPUBLIC = "czech_republic",
  DENMARK = "denmark",
  DJIBOUTI = "djibouti",
  DOMINICA = "dominica",
  DOMINICAN_REPUBLIC = "dominican_republic",
  ECUADOR = "ecuador",
  EGYPT = "egypt",
  EL_SALVADOR = "el_salvador",
  EQUATORIAL_GUINEA = "equatorial_guinea",
  ERITREA = "eritrea",
  ESTONIA = "estonia",
  ETHIOPIA = "ethiopia",
  FIJI = "fiji",
  FINLAND = "finland",
  FRANCE = "france",
  GABON = "gabon",
  GAMBIA = "gambia",
  GEORGIA = "georgia",
  GERMANY = "germany",
  GHANA = "ghana",
  GREECE = "greece",
  GRENADA = "grenada",
  GUATEMALA = "guatemala",
  GUINEA = "guinea",
  GUINEA_BISSAU = "guinea_bissau",
  GUYANA = "guyana",
  HAITI = "haiti",
  HONDURAS = "honduras",
  HUNGARY = "hungary",
  ICELAND = "iceland",
  INDIA = "india",
  INDONESIA = "indonesia",
  IRAN = "iran",
  IRAQ = "iraq",
  IRELAND = "ireland",
  ISRAEL = "israel",
  ITALY = "italy",
  JAMAICA = "jamaica",
  JAPAN = "japan",
  JORDAN = "jordan",
  KAZAKHSTAN = "kazakhstan",
  KENYA = "kenya",
  KIRIBATI = "kiribati",
  KOREA_NORTH = "korea_north",
  KOREA_SOUTH = "korea_south",
  KUWAIT = "kuwait",
  KYRGYZSTAN = "kyrgyzstan",
  LAOS = "laos",
  LATVIA = "latvia",
  LEBANON = "lebanon",
  LESOTHO = "lesotho",
  LIBERIA = "liberia",
  LIBYA = "libya",
  LIECHTENSTEIN = "liechtenstein",
  LITHUANIA = "lithuania",
  LUXEMBOURG = "luxembourg",
  MACEDONIA = "macedonia",
  MADAGASCAR = "madagascar",
  MALAWI = "malawi",
  MALAYSIA = "malaysia",
  MALDIVES = "maldives",
  MALI = "mali",
  MALTA = "malta",
  MARSHALL_ISLANDS = "marshall_islands",
  MAURITANIA = "mauritania",
  MAURITIUS = "mauritius",
  MEXICO = "mexico",
  MICRONESIA = "micronesia",
  MOLDOVA = "moldova",
  MONACO = "monaco",
  MONGOLIA = "mongolia",
  MONTENEGRO = "montenegro",
  MOROCCO = "morocco",
  MOZAMBIQUE = "mozambique",
  MYANMAR = "myanmar",
  NAMIBIA = "namibia",
  NAURU = "nauru",
  NEPAL = "nepal",
  NETHERLANDS = "netherlands",
  NEW_ZEALAND = "new_zealand",
  NICARAGUA = "nicaragua",
  NIGER = "niger",
  NIGERIA = "nigeria",
  NORWAY = "norway",
  OMAN = "oman",
  PAKISTAN = "pakistan",
  PALAU = "palau",
  PANAMA = "panama",
  PAPUA_NEW_GUINEA = "papua_new_guinea",
  PARAGUAY = "paraguay",
  PERU = "peru",
  POLAND = "poland",
  PORTUGAL = "portugal",
  QATAR = "qatar",
  ROMANIA = "romania",
  RUSSIAN_FEDERATION = "russian_federation",
  RWANDA = "rwanda",
  SAINT_KITTS_AND_NEVIS = "saint_kitts_and_nevis",
  SAINT_LUCIA = "saint_lucia",
  SAINT_VINCENT_AND_THE_GRENADINES = "saint_vincent_and_the_grenadines",
  SAMOA = "samoa",
  SAN_MARINO = "san_marino",
  SAO_TOME_AND_PRINCIPE = "sao_tome_and_principe",
  SAUDI_ARABIA = "saudi_arabia",
  SENEGAL = "senegal",
  SERBIA = "serbia",
  SEYCHELLES = "seychelles",
  SIERRA_LEONE = "sierra_leone",
  SINGAPORE = "singapore",
  SLOVAKIA = "slovakia",
  SLOVENIA = "slovenia",
  SOLOMON_ISLANDS = "solomon_islands",
  SOMALIA = "somalia",
  SOUTH_AFRICA = "south_africa",
  SOUTH_SUDAN = "south_sudan",
  SPAIN = "spain",
  SRI_LANKA = "sri_lanka",
  SUDAN = "sudan",
  SURINAME = "suriname",
  SWAZILAND = "swaziland",
  SWEDEN = "sweden",
  SWITZERLAND = "switzerland",
  SYRIA = "syria",
  TAIWAN = "taiwan",
  TAJIKISTAN = "tajikistan",
  TANZANIA = "tanzania",
  THAILAND = "thailand",
  TIMOR_LESTE = "timor_leste",
  TOGO = "togo",
  TONGA = "tonga",
  TRINIDAD_AND_TOBAGO = "trinidad_and_tobago",
  TUNISIA = "tunisia",
  TURKEY = "turkey",
  TURKMENISTAN = "turkmenistan",
  TUVALU = "tuvalu",
  UGANDA = "uganda",
  UKRAINE = "ukraine",
  UNITED_ARAB_EMIRATES = "united_arab_emirates",
  UNITED_KINGDOM = "united_kingdom",
  UNITED_STATES = "united_states",
  URUGUAY = "uruguay",
  UZBEKISTAN = "uzbekistan",
  VANUATU = "vanuatu",
  VATICAN_CITY = "vatican_city",
  VENEZUELA = "venezuela",
  VIETNAM = "vietnam",
  YEMEN = "yemen",
  ZAMBIA = "zambia",
  ZIMBABWE = "zimbabwe"
}

export const FrontendLabel: Record<string, string> = {
  [Enums.PHILIPPINES]: "PHILIPPINES",
  [Enums.AFGHANISTAN]: "AFGHANISTAN",
  [Enums.ALBANIA]: "ALBANIA",
  [Enums.ALGERIA]: "ALGERIA",
  [Enums.ANDORRA]: "ANDORRA",
  [Enums.ANGOLA]: "ANGOLA",
  [Enums.ANTIGUA_AND_BARBUDA]: "ANTIGUA AND BARBUDA",
  [Enums.ARGENTINA]: "ARGENTINA",
  [Enums.ARMENIA]: "ARMENIA",
  [Enums.AUSTRALIA]: "AUSTRALIA",
  [Enums.AUSTRIA]: "AUSTRIA",
  [Enums.AZERBAIJAN]: "AZERBAIJAN",
  [Enums.BAHAMAS]: "BAHAMAS",
  [Enums.BAHRAIN]: "BAHRAIN",
  [Enums.BANGLADESH]: "BANGLADESH",
  [Enums.BARBADOS]: "BARBADOS",
  [Enums.BELARUS]: "BELARUS",
  [Enums.BELGIUM]: "BELGIUM",
  [Enums.BELIZE]: "BELIZE",
  [Enums.BENIN]: "BENIN",
  [Enums.BHUTAN]: "BHUTAN",
  [Enums.BOLIVIA]: "BOLIVIA",
  [Enums.BOSNIA_AND_HERZEGOVINA]: "BOSNIA AND HERZEGOVINA",
  [Enums.BOTSWANA]: "BOTSWANA",
  [Enums.BRAZIL]: "BRAZIL",
  [Enums.BRUNEI]: "BRUNEI",
  [Enums.BULGARIA]: "BULGARIA",
  [Enums.BURKINA_FASO]: "BURKINA FASO",
  [Enums.BURUNDI]: "BURUNDI",
  [Enums.CAMBODIA]: "CAMBODIA",
  [Enums.CAMEROON]: "CAMEROON",
  [Enums.CANADA]: "CANADA",
  [Enums.CAPE_VERDE]: "CAPE VERDE",
  [Enums.CENTRAL_AFRICAN_REPUBLIC]: "CENTRAL AFRICAN REPUBLIC",
  [Enums.CHAD]: "CHAD",
  [Enums.CHILE]: "CHILE",
  [Enums.CHINA]: "CHINA",
  [Enums.COLOMBIA]: "COLOMBIA",
  [Enums.COMOROS]: "COMOROS",
  [Enums.CONGO]: "CONGO",
  [Enums.COSTA_RICA]: "COSTA RICA",
  [Enums.CROATIA]: "CROATIA",
  [Enums.CUBA]: "CUBA",
  [Enums.CYPRUS]: "CYPRUS",
  [Enums.CZECH_REPUBLIC]: "CZECH REPUBLIC",
  [Enums.DENMARK]: "DENMARK",
  [Enums.DJIBOUTI]: "DJIBOUTI",
  [Enums.DOMINICA]: "DOMINICA",
  [Enums.DOMINICAN_REPUBLIC]: "DOMINICAN REPUBLIC",
  [Enums.ECUADOR]: "ECUADOR",
  [Enums.EGYPT]: "EGYPT",
  [Enums.EL_SALVADOR]: "EL SALVADOR",
  [Enums.EQUATORIAL_GUINEA]: "EQUATORIAL GUINEA",
  [Enums.ERITREA]: "ERITREA",
  [Enums.ESTONIA]: "ESTONIA",
  [Enums.ETHIOPIA]: "ETHIOPIA",
  [Enums.FIJI]: "FIJI",
  [Enums.FINLAND]: "FINLAND",
  [Enums.FRANCE]: "FRANCE",
  [Enums.GABON]: "GABON",
  [Enums.GAMBIA]: "GAMBIA",
  [Enums.GEORGIA]: "GEORGIA",
  [Enums.GERMANY]: "GERMANY",
  [Enums.GHANA]: "GHANA",
  [Enums.GREECE]: "GREECE",
  [Enums.GRENADA]: "GRENADA",
  [Enums.GUATEMALA]: "GUATEMALA",
  [Enums.GUINEA]: "GUINEA",
  [Enums.GUINEA_BISSAU]: "GUINEA BISSAU",
  [Enums.GUYANA]: "GUYANA",
  [Enums.HAITI]: "HAITI",
  [Enums.HONDURAS]: "HONDURAS",
  [Enums.HUNGARY]: "HUNGARY",
  [Enums.ICELAND]: "ICELAND",
  [Enums.INDIA]: "INDIA",
  [Enums.INDONESIA]: "INDONESIA",
  [Enums.IRAN]: "IRAN",
  [Enums.IRAQ]: "IRAQ",
  [Enums.IRELAND]: "IRELAND",
  [Enums.ISRAEL]: "ISRAEL",
  [Enums.ITALY]: "ITALY",
  [Enums.JAMAICA]: "JAMAICA",
  [Enums.JAPAN]: "JAPAN",
  [Enums.JORDAN]: "JORDAN",
  [Enums.KAZAKHSTAN]: "KAZAKHSTAN",
  [Enums.KENYA]: "KENYA",
  [Enums.KIRIBATI]: "KIRIBATI",
  [Enums.KOREA_NORTH]: "KOREA NORTH",
  [Enums.KOREA_SOUTH]: "KOREA SOUTH",
  [Enums.KUWAIT]: "KUWAIT",
  [Enums.KYRGYZSTAN]: "KYRGYZSTAN",
  [Enums.LAOS]: "LAOS",
  [Enums.LATVIA]: "LATVIA",
  [Enums.LEBANON]: "LEBANON",
  [Enums.LESOTHO]: "LESOTHO",
  [Enums.LIBERIA]: "LIBERIA",
  [Enums.LIBYA]: "LIBYA",
  [Enums.LIECHTENSTEIN]: "LIECHTENSTEIN",
  [Enums.LITHUANIA]: "LITHUANIA",
  [Enums.LUXEMBOURG]: "LUXEMBOURG",
  [Enums.MACEDONIA]: "MACEDONIA",
  [Enums.MADAGASCAR]: "MADAGASCAR",
  [Enums.MALAWI]: "MALAWI",
  [Enums.MALAYSIA]: "MALAYSIA",
  [Enums.MALDIVES]: "MALDIVES",
  [Enums.MALI]: "MALI",
  [Enums.MALTA]: "MALTA",
  [Enums.MARSHALL_ISLANDS]: "MARSHALL ISLANDS",
  [Enums.MAURITANIA]: "MAURITANIA",
  [Enums.MAURITIUS]: "MAURITIUS",
  [Enums.MEXICO]: "MEXICO",
  [Enums.MICRONESIA]: "MICRONESIA",
  [Enums.MOLDOVA]: "MOLDOVA",
  [Enums.MONACO]: "MONACO",
  [Enums.MONGOLIA]: "MONGOLIA",
  [Enums.MONTENEGRO]: "MONTENEGRO",
  [Enums.MOROCCO]: "MOROCCO",
  [Enums.MOZAMBIQUE]: "MOZAMBIQUE",
  [Enums.MYANMAR]: "MYANMAR",
  [Enums.NAMIBIA]: "NAMIBIA",
  [Enums.NAURU]: "NAURU",
  [Enums.NEPAL]: "NEPAL",
  [Enums.NETHERLANDS]: "NETHERLANDS",
  [Enums.NEW_ZEALAND]: "NEW ZEALAND",
  [Enums.NICARAGUA]: "NICARAGUA",
  [Enums.NIGER]: "NIGER",
  [Enums.NIGERIA]: "NIGERIA",
  [Enums.NORWAY]: "NORWAY",
  [Enums.OMAN]: "OMAN",
  [Enums.PAKISTAN]: "PAKISTAN",
  [Enums.PALAU]: "PALAU",
  [Enums.PANAMA]: "PANAMA",
  [Enums.PAPUA_NEW_GUINEA]: "PAPUA NEW GUINEA",
  [Enums.PARAGUAY]: "PARAGUAY",
  [Enums.PERU]: "PERU",
  [Enums.POLAND]: "POLAND",
  [Enums.PORTUGAL]: "PORTUGAL",
  [Enums.QATAR]: "QATAR",
  [Enums.ROMANIA]: "ROMANIA",
  [Enums.RUSSIAN_FEDERATION]: "RUSSIAN FEDERATION",
  [Enums.RWANDA]: "RWANDA",
  [Enums.SAINT_KITTS_AND_NEVIS]: "SAINT KITTS AND NEVIS",
  [Enums.SAINT_LUCIA]: "SAINT LUCIA",
  [Enums.SAINT_VINCENT_AND_THE_GRENADINES]: "SAINT VINCENT AND THE GRENADINES",
  [Enums.SAMOA]: "SAMOA",
  [Enums.SAN_MARINO]: "SAN MARINO",
  [Enums.SAO_TOME_AND_PRINCIPE]: "SAO TOME AND PRINCIPE",
  [Enums.SAUDI_ARABIA]: "SAUDI ARABIA",
  [Enums.SENEGAL]: "SENEGAL",
  [Enums.SERBIA]: "SERBIA",
  [Enums.SEYCHELLES]: "SEYCHELLES",
  [Enums.SIERRA_LEONE]: "SIERRA LEONE",
  [Enums.SINGAPORE]: "SINGAPORE",
  [Enums.SLOVAKIA]: "SLOVAKIA",
  [Enums.SLOVENIA]: "SLOVENIA",
  [Enums.SOLOMON_ISLANDS]: "SOLOMON ISLANDS",
  [Enums.SOMALIA]: "SOMALIA",
  [Enums.SOUTH_AFRICA]: "SOUTH AFRICA",
  [Enums.SOUTH_SUDAN]: "SOUTH SUDAN",
  [Enums.SPAIN]: "SPAIN",
  [Enums.SRI_LANKA]: "SRI LANKA",
  [Enums.SUDAN]: "SUDAN",
  [Enums.SURINAME]: "SURINAME",
  [Enums.SWAZILAND]: "SWAZILAND",
  [Enums.SWEDEN]: "SWEDEN",
  [Enums.SWITZERLAND]: "SWITZERLAND",
  [Enums.SYRIA]: "SYRIA",
  [Enums.TAIWAN]: "TAIWAN",
  [Enums.TAJIKISTAN]: "TAJIKISTAN",
  [Enums.TANZANIA]: "TANZANIA",
  [Enums.THAILAND]: "THAILAND",
  [Enums.TIMOR_LESTE]: "TIMOR-LESTE",
  [Enums.TOGO]: "TOGO",
  [Enums.TONGA]: "TONGA",
  [Enums.TRINIDAD_AND_TOBAGO]: "TRINIDAD AND TOBAGO",
  [Enums.TUNISIA]: "TUNISIA",
  [Enums.TURKEY]: "TURKEY",
  [Enums.TURKMENISTAN]: "TURKMENISTAN",
  [Enums.TUVALU]: "TUVALU",
  [Enums.UGANDA]: "UGANDA",
  [Enums.UKRAINE]: "UKRAINE",
  [Enums.UNITED_ARAB_EMIRATES]: "UNITED ARAB EMIRATES",
  [Enums.UNITED_KINGDOM]: "UNITED KINGDOM",
  [Enums.UNITED_STATES]: "UNITED STATES",
  [Enums.URUGUAY]: "URUGUAY",
  [Enums.UZBEKISTAN]: "UZBEKISTAN",
  [Enums.VANUATU]: "VANUATU",
  [Enums.VATICAN_CITY]: "VATICAN CITY",
  [Enums.VENEZUELA]: "VENEZUELA",
  [Enums.VIETNAM]: "VIETNAM",
  [Enums.YEMEN]: "YEMEN",
  [Enums.ZAMBIA]: "ZAMBIA",
  [Enums.ZIMBABWE]: "ZIMBABWE"
}

export const Dropdown = computed(() => {
  return Object.keys(Enums).map((key) => ({
    label: FrontendLabel[Enums[key as keyof typeof Enums]],
    value: Enums[key as keyof typeof Enums]
  }))
})
