import { computed } from "vue"

export enum Enums {
  ACCOUNTANCY = "accountancy",
  ADVERSTING_MARKETING = "adversting_marketing",
  AGRICUTURE = "agricuture",
  AUTOMOTIVE_SHIP_BUILDING = "automotive_ship_building",
  BANKING_FINANCE = "banking_finance",
  BPO_IT = "bpo_it",
  CHARITIES = "charities",
  COMMUNICATION = "communication",
  CONSTRUCTION = "construction",
  EDUCATION = "education",
  ENERGY = "energy",
  ENTERTAIMENT = "entertaiment",
  FOOD_SERVICE = "food_service",
  FOEWARDING_CUSTOMS_BROKERAGE_WAREHOUSING = "foewarding_customs_brokerage_warehousing",
  GAMING = "gaming",
  GOVERNMENT = "government",
  HEALTHCARE_MADICINE = "healthcare_madicine",
  INSURANCE = "insurance",
  JEWELRY_PRECIOUS_STONES_MEAL_TRADING = "jewelry_precious_stones_meal_trading",
  JOURNALISM = "journalism",
  LEGAL = "legal",
  MANUFACTURING = "manufacturing",
  MINING = "mining",
  MONEY_SERVICES = "money_services",
  NONPROFIT_ORGANIZATION = "nonprofit_organization",
  OVERSEAS_WORK = "overseas_work",
  REAL_ESTATE = "real_estate",
  RETAIL_TRADING = "retail_trading",
  SALES = "sales",
  SECURITIES_STOCKS_BROKERAGE = "securities_stocks_brokerage",
  SECURITY_ENFORVEMENT = "security_enforvement",
  TOURISM = "tourism",
  TRANSPORTATION = "transportation",
  UNEMPLOYED = "unemployed",
  OTHER = "other"
}

export const FrontendLabel: Record<string, string> = {
  [Enums.ACCOUNTANCY]: "ACCOUNTANCY",
  [Enums.ADVERSTING_MARKETING]: "ADVERSTING MARKETING",
  [Enums.AGRICUTURE]: "AGRICUTURE",
  [Enums.AUTOMOTIVE_SHIP_BUILDING]: "AUTOMOTIVE SHIP BUILDING",
  [Enums.BANKING_FINANCE]: "BANKING FINANCE",
  [Enums.BPO_IT]: "BPO IT",
  [Enums.CHARITIES]: "CHARITIES",
  [Enums.COMMUNICATION]: "COMMUNICATION",
  [Enums.CONSTRUCTION]: "CONSTRUCTION",
  [Enums.EDUCATION]: "EDUCATION",
  [Enums.ENERGY]: "ENERGY",
  [Enums.ENTERTAIMENT]: "ENTERTAIMENT",
  [Enums.FOOD_SERVICE]: "FOOD SERVICE",
  [Enums.FOEWARDING_CUSTOMS_BROKERAGE_WAREHOUSING]: "FOEWARDING CUSTOMS BROKERAGE WAREHOUSING",
  [Enums.GAMING]: "GAMING",
  [Enums.GOVERNMENT]: "GOVERNMENT",
  [Enums.HEALTHCARE_MADICINE]: "HEALTHCARE MADICINE",
  [Enums.INSURANCE]: "INSURANCE",
  [Enums.JEWELRY_PRECIOUS_STONES_MEAL_TRADING]: "JEWELRY PRECIOUS STONES MEAL TRADING",
  [Enums.JOURNALISM]: "JOURNALISM",
  [Enums.LEGAL]: "LEGAL",
  [Enums.MANUFACTURING]: "MANUFACTURING",
  [Enums.MINING]: "MINING",
  [Enums.MONEY_SERVICES]: "MONEY SERVICES",
  [Enums.NONPROFIT_ORGANIZATION]: "NONPROFIT ORGANIZATION",
  [Enums.OVERSEAS_WORK]: "OVERSEAS WORK",
  [Enums.REAL_ESTATE]: "REAL ESTATE",
  [Enums.RETAIL_TRADING]: "RETAIL TRADING",
  [Enums.SALES]: "SALES",
  [Enums.SECURITIES_STOCKS_BROKERAGE]: "SECURITIES STOCKS BROKERAGE",
  [Enums.SECURITY_ENFORVEMENT]: "SECURITY ENFORVEMENT",
  [Enums.TOURISM]: "TOURISM",
  [Enums.TRANSPORTATION]: "TRANSPORTATION",
  [Enums.UNEMPLOYED]: "UNEMPLOYED",
  [Enums.OTHER]: "OTHER"
}

export const Dropdown = computed(() => {
  return Object.keys(Enums).map((key) => ({
    label: FrontendLabel[Enums[key as keyof typeof Enums]],
    value: Enums[key as keyof typeof Enums]
  }))
})
