export const environment = {
  production: false,
  uVersion: "u1",
  mVersion: "m3",
  mvVersion: "res_template",
  mockBackend: false,
  platformName: "Dev U1M3",
  platformGroup: "O TT Group",
  baseUrl: "",
  appPackageName: "com.ttgroup.phxj",
  captcha: "/japi/user/captcha/image",
  appVersion: "1.0.2",
  s3URLImages: "https://resources.ttgroup.vip/icon",
  snowEffects: "none",
};
