import { CURRENCY_TYPE } from "@/utils/constants"
import * as Response from "@/api/response.type"

export const memberList: Response.GetMemberList = [
  {
    id: 10,
    account: "s0293",
    recommender: "efnf",
    member_level: 1,
    member_tag: 5,
    enable_or_disable: 1,
    last_login_time: 1693295184381,
    registration_time: 1693295184381,
    account_frozen: false
  },
  {
    id: 12,
    account: "s0293",
    recommender: "jhow",
    member_level: 1,
    member_tag: 4,
    enable_or_disable: 1,
    last_login_time: 1694431921753,
    registration_time: 1694431921753,
    account_frozen: true
  },
  {
    id: 13,
    account: "s0350",
    recommender: "efnf",
    member_level: 1,
    member_tag: 2,
    enable_or_disable: 0,
    last_login_time: 1694664563769,
    registration_time: 1694664563769,
    account_frozen: false
  },
  {
    id: 14,
    account: "CMS",
    recommender: "test",
    member_level: 1,
    member_tag: 1,
    enable_or_disable: 0,
    last_login_time: 1694877581363,
    registration_time: 1694877581363,
    account_frozen: false
  },
  {
    id: 15,
    account: "CMS1",
    recommender: "test",
    member_level: 1,
    member_tag: 1,
    enable_or_disable: 1,
    last_login_time: 1694877821327,
    registration_time: 1694877821327,
    account_frozen: false
  },
  {
    id: 16,
    account: "CMS2",
    recommender: "test",
    member_level: 1,
    member_tag: 2,
    enable_or_disable: 1,
    last_login_time: 1694877889263,
    registration_time: 1694877889263,
    account_frozen: false
  },
  {
    id: 17,
    account: "CMS3",
    recommender: "test",
    member_level: 1,
    member_tag: 1,
    enable_or_disable: 1,
    last_login_time: 1694878037101,
    registration_time: 1694878037101,
    account_frozen: true
  },
  {
    id: 18,
    account: "s0351",
    recommender: "efnf",
    member_level: 1,
    member_tag: 2,
    enable_or_disable: 1,
    last_login_time: 1695042264655,
    registration_time: 1695042264655,
    account_frozen: false
  },
  {
    id: 19,
    account: "s0352",
    recommender: "efnf",
    member_level: 1,
    member_tag: 2,
    enable_or_disable: 1,
    last_login_time: 1695043219136,
    registration_time: 1695043219136,
    account_frozen: false
  },
  {
    id: 20,
    account: "s0355",
    recommender: "efnf",
    member_level: 1,
    member_tag: 1,
    enable_or_disable: 1,
    last_login_time: 1695043325175,
    registration_time: 1695043325175,
    account_frozen: false
  },
  {
    id: 21,
    account: "s0250",
    recommender: "efnf",
    member_level: 1,
    member_tag: 1,
    enable_or_disable: 1,
    last_login_time: 1695107290236,
    registration_time: 1695107290236,
    account_frozen: true
  }
]

export const memberInformation: Response.GetMemberInformation = [
  {
    id: 10,
    account: "s02934",
    password: "123",
    recommender: "efnf",
    member_level: 1,
    member_tag: 5,
    enable_or_disable: 1,
    last_login_time: 1693295184381,
    registration_time: 1693295184381,
    account_frozen: false,
    register_method: "會員端註冊",
    last_login_ip: "111.111.111",
    last_deposit_time: 1693295184381,
    last_withdrawal_time: 1693295184381,
    countryCode: "+86",
    referral_code: "atest7web.efinitywl.com/Home/Register?Referral=ATEST7_Testing",
    php: 100,
    kvnd: 0,
    sgd: 0,
    myr: 0,
    rmb: 0,
    thb: 0,
    usdt: 0,
    idr: 0,
    realName: "Eric",
    nickName: "",
    birthDay: 1693295184381,
    gender: 1,
    phone: "0988888888",
    email: "test@gmail.com",
    communicationSoftware1: "Line",
    communicationSoftware2: "Skype",
    blockDepositTags: [],
    blockWithdrawalTags: [],
    blockPromotionTags: []
  },
  {
    id: 12,
    account: "s0293",
    password: "123",
    recommender: "jhow",
    member_level: 1,
    member_tag: 4,
    enable_or_disable: 1,
    last_login_time: 1694431921753,
    registration_time: 1694431921753,
    account_frozen: true,
    register_method: "會員端註冊",
    last_login_ip: "111.111.111",
    last_deposit_time: 1693295184381,
    last_withdrawal_time: 1693295184381,
    countryCode: "+86",
    referral_code: "atest7web.efinitywl.com/Home/Register?Referral=ATEST7_Testing",
    php: 0,
    kvnd: 0,
    sgd: 0,
    myr: 0,
    rmb: 0,
    thb: 0,
    usdt: 0,
    idr: 0,
    realName: "Eric",
    nickName: "",
    birthDay: 1693295184381,
    gender: 1,
    phone: "0988888888",
    email: "test@gmail.com",
    communicationSoftware1: "Line",
    communicationSoftware2: "Skype",
    blockDepositTags: [],
    blockWithdrawalTags: [],
    blockPromotionTags: []
  },
  {
    id: 13,
    account: "s0350",
    password: "123",
    recommender: "efnf",
    member_level: 1,
    member_tag: 2,
    enable_or_disable: 0,
    last_login_time: 1694664563769,
    registration_time: 1694664563769,
    account_frozen: false,
    register_method: "會員端註冊",
    last_login_ip: "111.111.111",
    last_deposit_time: 1693295184381,
    last_withdrawal_time: 1693295184381,
    countryCode: "+86",
    referral_code: "atest7web.efinitywl.com/Home/Register?Referral=ATEST7_Testing",
    php: 0,
    kvnd: 0,
    sgd: 0,
    myr: 0,
    rmb: 0,
    thb: 0,
    usdt: 0,
    idr: 0,
    realName: "Eric",
    nickName: "",
    birthDay: 1693295184381,
    gender: 1,
    phone: "0988888888",
    email: "test@gmail.com",
    communicationSoftware1: "Line",
    communicationSoftware2: "Skype",
    blockDepositTags: [],
    blockWithdrawalTags: [],
    blockPromotionTags: []
  },
  {
    id: 14,
    account: "CMS",
    password: "123",
    recommender: "test",
    member_level: 1,
    member_tag: 1,
    enable_or_disable: 0,
    last_login_time: 1694877581363,
    registration_time: 1694877581363,
    account_frozen: false,
    register_method: "會員端註冊",
    last_login_ip: "111.111.111",
    last_deposit_time: 1693295184381,
    last_withdrawal_time: 1693295184381,
    countryCode: "+86",
    referral_code: "atest7web.efinitywl.com/Home/Register?Referral=ATEST7_Testing",
    php: 0,
    kvnd: 0,
    sgd: 0,
    myr: 0,
    rmb: 0,
    thb: 0,
    usdt: 0,
    idr: 0,
    realName: "Eric",
    nickName: "",
    birthDay: 1693295184381,
    gender: 1,
    phone: "0988888888",
    email: "test@gmail.com",
    communicationSoftware1: "Line",
    communicationSoftware2: "Skype",
    blockDepositTags: [],
    blockWithdrawalTags: [],
    blockPromotionTags: []
  },
  {
    id: 15,
    account: "CMS1",
    password: "123",
    recommender: "test",
    member_level: 1,
    member_tag: 1,
    enable_or_disable: 1,
    last_login_time: 1694877821327,
    registration_time: 1694877821327,
    account_frozen: false,
    register_method: "會員端註冊",
    last_login_ip: "111.111.111",
    last_deposit_time: 1693295184381,
    last_withdrawal_time: 1693295184381,
    countryCode: "+86",
    referral_code: "atest7web.efinitywl.com/Home/Register?Referral=ATEST7_Testing",
    php: 0,
    kvnd: 0,
    sgd: 0,
    myr: 0,
    rmb: 0,
    thb: 0,
    usdt: 0,
    idr: 0,
    realName: "Eric",
    nickName: "",
    birthDay: 1693295184381,
    gender: 1,
    phone: "0988888888",
    email: "test@gmail.com",
    communicationSoftware1: "Line",
    communicationSoftware2: "Skype",
    blockDepositTags: [],
    blockWithdrawalTags: [],
    blockPromotionTags: []
  },
  {
    id: 16,
    account: "CMS2",
    password: "123",
    recommender: "test",
    member_level: 1,
    member_tag: 2,
    enable_or_disable: 1,
    last_login_time: 1694877889263,
    registration_time: 1694877889263,
    account_frozen: false,
    register_method: "會員端註冊",
    last_login_ip: "111.111.111",
    last_deposit_time: 1693295184381,
    last_withdrawal_time: 1693295184381,
    countryCode: "+86",
    referral_code: "atest7web.efinitywl.com/Home/Register?Referral=ATEST7_Testing",
    php: 0,
    kvnd: 0,
    sgd: 0,
    myr: 0,
    rmb: 0,
    thb: 0,
    usdt: 0,
    idr: 0,
    realName: "Eric",
    nickName: "",
    birthDay: 1693295184381,
    gender: 1,
    phone: "0988888888",
    email: "test@gmail.com",
    communicationSoftware1: "Line",
    communicationSoftware2: "Skype",
    blockDepositTags: [],
    blockWithdrawalTags: [],
    blockPromotionTags: []
  },
  {
    id: 17,
    account: "CMS3",
    password: "123",
    recommender: "test",
    member_level: 1,
    member_tag: 1,
    enable_or_disable: 1,
    last_login_time: 1694878037101,
    registration_time: 1694878037101,
    account_frozen: true,
    register_method: "會員端註冊",
    last_login_ip: "111.111.111",
    last_deposit_time: 1693295184381,
    last_withdrawal_time: 1693295184381,
    countryCode: "+86",
    referral_code: "atest7web.efinitywl.com/Home/Register?Referral=ATEST7_Testing",
    php: 0,
    kvnd: 0,
    sgd: 0,
    myr: 0,
    rmb: 0,
    thb: 0,
    usdt: 0,
    idr: 0,
    realName: "Eric",
    nickName: "",
    birthDay: 1693295184381,
    gender: 1,
    phone: "0988888888",
    email: "test@gmail.com",
    communicationSoftware1: "Line",
    communicationSoftware2: "Skype",
    blockDepositTags: [],
    blockWithdrawalTags: [],
    blockPromotionTags: []
  },
  {
    id: 18,
    account: "s0351",
    password: "123",
    recommender: "efnf",
    member_level: 1,
    member_tag: 2,
    enable_or_disable: 1,
    last_login_time: 1695042264655,
    registration_time: 1695042264655,
    account_frozen: false,
    register_method: "會員端註冊",
    last_login_ip: "111.111.111",
    last_deposit_time: 1693295184381,
    last_withdrawal_time: 1693295184381,
    countryCode: "+86",
    referral_code: "atest7web.efinitywl.com/Home/Register?Referral=ATEST7_Testing",
    php: 0,
    kvnd: 0,
    sgd: 0,
    myr: 0,
    rmb: 0,
    thb: 0,
    usdt: 0,
    idr: 0,
    realName: "Eric",
    nickName: "",
    birthDay: 1693295184381,
    gender: 1,
    phone: "0988888888",
    email: "test@gmail.com",
    communicationSoftware1: "Line",
    communicationSoftware2: "Skype",
    blockDepositTags: [],
    blockWithdrawalTags: [],
    blockPromotionTags: []
  },
  {
    id: 19,
    account: "s0352",
    password: "123",
    recommender: "efnf",
    member_level: 1,
    member_tag: 2,
    enable_or_disable: 1,
    last_login_time: 1695043219136,
    registration_time: 1695043219136,
    account_frozen: false,
    register_method: "會員端註冊",
    last_login_ip: "111.111.111",
    last_deposit_time: 1693295184381,
    last_withdrawal_time: 1693295184381,
    countryCode: "+86",
    referral_code: "atest7web.efinitywl.com/Home/Register?Referral=ATEST7_Testing",
    php: 0,
    kvnd: 0,
    sgd: 0,
    myr: 0,
    rmb: 0,
    thb: 0,
    usdt: 0,
    idr: 0,
    realName: "Eric",
    nickName: "",
    birthDay: 1693295184381,
    gender: 1,
    phone: "0988888888",
    email: "test@gmail.com",
    communicationSoftware1: "Line",
    communicationSoftware2: "Skype",
    blockDepositTags: [],
    blockWithdrawalTags: [],
    blockPromotionTags: []
  },
  {
    id: 20,
    account: "s0355",
    password: "123",
    recommender: "efnf",
    member_level: 1,
    member_tag: 1,
    enable_or_disable: 1,
    last_login_time: 1695043325175,
    registration_time: 1695043325175,
    account_frozen: false,
    register_method: "會員端註冊",
    last_login_ip: "111.111.111",
    last_deposit_time: 1693295184381,
    last_withdrawal_time: 1693295184381,
    countryCode: "+86",
    referral_code: "atest7web.efinitywl.com/Home/Register?Referral=ATEST7_Testing",
    php: 0,
    kvnd: 0,
    sgd: 0,
    myr: 0,
    rmb: 0,
    thb: 0,
    usdt: 0,
    idr: 0,
    realName: "Eric",
    nickName: "",
    birthDay: 1693295184381,
    gender: 1,
    phone: "0988888888",
    email: "test@gmail.com",
    communicationSoftware1: "Line",
    communicationSoftware2: "Skype",
    blockDepositTags: [],
    blockWithdrawalTags: [],
    blockPromotionTags: []
  },
  {
    id: 21,
    account: "s0250",
    password: "123",
    recommender: "efnf",
    member_level: 1,
    member_tag: 1,
    enable_or_disable: 1,
    last_login_time: 1695107290236,
    registration_time: 1695107290236,
    account_frozen: true,
    register_method: "會員端註冊",
    last_login_ip: "111.111.111",
    last_deposit_time: 1693295184381,
    last_withdrawal_time: 1693295184381,
    countryCode: "+86",
    referral_code: "atest7web.efinitywl.com/Home/Register?Referral=ATEST7_Testing",
    php: 0,
    kvnd: 0,
    sgd: 0,
    myr: 0,
    rmb: 0,
    thb: 0,
    usdt: 0,
    idr: 0,
    realName: "Eric",
    nickName: "",
    birthDay: 1693295184381,
    gender: 1,
    phone: "0988888888",
    email: "test@gmail.com",
    communicationSoftware1: "Line",
    communicationSoftware2: "Skype",
    blockDepositTags: [],
    blockWithdrawalTags: [],
    blockPromotionTags: []
  }
]

export const memberLevel: Response.GetMemberLevel = [
  {
    id: 10,
    type: "english",
    title: "黃金VIP",
    remark: "",
    promotion: [],
    withdrawal_setting: [],
    withdrawal_limit: [],
    deposit_bank_card: [],
    deposit_electronic_wallet: [],
    deposit_third_payment: [],
    withdraw_bank_card: [],
    withdraw_electronic_wallet: [],
    withdraw_third_payment: []
  },
  {
    id: 12,
    type: "english",
    title: "黃金VIP",
    remark: "",
    promotion: [],
    withdrawal_setting: [],
    withdrawal_limit: [],
    deposit_bank_card: [],
    deposit_electronic_wallet: [],
    deposit_third_payment: [],
    withdraw_bank_card: [],
    withdraw_electronic_wallet: [],
    withdraw_third_payment: []
  },
  {
    id: 13,
    type: "english",
    title: "黃金VIP",
    remark: "",
    promotion: [],
    withdrawal_setting: [],
    withdrawal_limit: [],
    deposit_bank_card: [],
    deposit_electronic_wallet: [],
    deposit_third_payment: [],
    withdraw_bank_card: [],
    withdraw_electronic_wallet: [],
    withdraw_third_payment: []
  },
  {
    id: 14,
    type: "english",
    title: "黃金VIP",
    remark: "",
    promotion: [],
    withdrawal_setting: [],
    withdrawal_limit: [],
    deposit_bank_card: [],
    deposit_electronic_wallet: [],
    deposit_third_payment: [],
    withdraw_bank_card: [],
    withdraw_electronic_wallet: [],
    withdraw_third_payment: []
  },
  {
    id: 15,
    type: "english",
    title: "黃金VIP",
    remark: "",
    promotion: [],
    withdrawal_setting: [],
    withdrawal_limit: [],
    deposit_bank_card: [],
    deposit_electronic_wallet: [],
    deposit_third_payment: [],
    withdraw_bank_card: [],
    withdraw_electronic_wallet: [],
    withdraw_third_payment: []
  },
  {
    id: 16,
    type: "english",
    title: "黃金VIP",
    remark: "",
    promotion: [],
    withdrawal_setting: [],
    withdrawal_limit: [],
    deposit_bank_card: [],
    deposit_electronic_wallet: [],
    deposit_third_payment: [],
    withdraw_bank_card: [],
    withdraw_electronic_wallet: [],
    withdraw_third_payment: []
  },
  {
    id: 17,
    type: "english",
    title: "黃金VIP",
    remark: "",
    promotion: [],
    withdrawal_setting: [],
    withdrawal_limit: [],
    deposit_bank_card: [],
    deposit_electronic_wallet: [],
    deposit_third_payment: [],
    withdraw_bank_card: [],
    withdraw_electronic_wallet: [],
    withdraw_third_payment: []
  },
  {
    id: 18,
    type: "english",
    title: "黃金VIP",
    remark: "",
    promotion: [],
    withdrawal_setting: [],
    withdrawal_limit: [],
    deposit_bank_card: [],
    deposit_electronic_wallet: [],
    deposit_third_payment: [],
    withdraw_bank_card: [],
    withdraw_electronic_wallet: [],
    withdraw_third_payment: []
  },
  {
    id: 19,
    type: "english",
    title: "黃金VIP",
    remark: "",
    promotion: [],
    withdrawal_setting: [],
    withdrawal_limit: [],
    deposit_bank_card: [],
    deposit_electronic_wallet: [],
    deposit_third_payment: [],
    withdraw_bank_card: [],
    withdraw_electronic_wallet: [],
    withdraw_third_payment: []
  },
  {
    id: 20,
    type: "english",
    title: "黃金VIP",
    remark: "",
    promotion: [],
    withdrawal_setting: [],
    withdrawal_limit: [],
    deposit_bank_card: [],
    deposit_electronic_wallet: [],
    deposit_third_payment: [],
    withdraw_bank_card: [],
    withdraw_electronic_wallet: [],
    withdraw_third_payment: []
  },
  {
    id: 21,
    type: "english",
    title: "黃金VIP",
    remark: "",
    promotion: [],
    withdrawal_setting: [],
    withdrawal_limit: [],
    deposit_bank_card: [],
    deposit_electronic_wallet: [],
    deposit_third_payment: [],
    withdraw_bank_card: [],
    withdraw_electronic_wallet: [],
    withdraw_third_payment: []
  }
]

export const memberLevelDetail: Response.GetMemberLevelDetail = {
  level_name: {
    英: "",
    泰: "",
    印: "",
    越: "",
    簡: "",
    繁: ""
  },
  remark: "",
  level_up_settings: [
    {
      currency: CURRENCY_TYPE.Enums.USD,
      valid_betting: 100000,
      deposit_amount: 100000,
      level_up_reward: 100000,
      birthday_reward: 100000
    },
    {
      currency: CURRENCY_TYPE.Enums.SGD,
      valid_betting: 100000,
      deposit_amount: 100000,
      level_up_reward: 100000,
      birthday_reward: 100000
    },
    {
      currency: CURRENCY_TYPE.Enums.TWD,
      valid_betting: 100000,
      deposit_amount: 100000,
      level_up_reward: 100000,
      birthday_reward: 100000
    },
    {
      currency: CURRENCY_TYPE.Enums.MYR,
      valid_betting: 100000,
      deposit_amount: 100000,
      level_up_reward: 100000,
      birthday_reward: 100000
    },
    {
      currency: CURRENCY_TYPE.Enums.IDR,
      valid_betting: 100000,
      deposit_amount: 100000,
      level_up_reward: 100000,
      birthday_reward: 100000
    }
  ],
  withdraw_settings: [
    {
      currency: CURRENCY_TYPE.Enums.USD,
      single_limit_min: 0,
      single_limit_max: 100000,
      single_day_limit: 50000,
      withdraw_num: 10
    },
    {
      currency: CURRENCY_TYPE.Enums.SGD,
      single_limit_min: 0,
      single_limit_max: 100000,
      single_day_limit: 50000,
      withdraw_num: 10
    },
    {
      currency: CURRENCY_TYPE.Enums.TWD,
      single_limit_min: 0,
      single_limit_max: 100000,
      single_day_limit: 50000,
      withdraw_num: 10
    },
    {
      currency: CURRENCY_TYPE.Enums.MYR,
      single_limit_min: 0,
      single_limit_max: 100000,
      single_day_limit: 50000,
      withdraw_num: 10
    },
    {
      currency: CURRENCY_TYPE.Enums.IDR,
      single_limit_min: 0,
      single_limit_max: 100000,
      single_day_limit: 50000,
      withdraw_num: 10
    }
  ]
}
