export const handleSubordinateDataLevelClick = 'handleSubordinateDataLevelClick';
export const handleSubordinateDataSortByJoinTimeClick = 'handleSubordinateDataSortByJoinTimeClick';
export const handleSubordinateDataSortByCommissionClick = 'handleSubordinateDataSortByCommissionClick';
export const handleSubordinateDataDisplayDatePickerClick = 'handleSubordinateDataDisplayDatePickerClick';
export const handleSubordinateDataMobileInputValueChange = 'handleSubordinateDataMobileInputValueChange';
export const handleSubordinateDataMobileSearchClick = 'handleSubordinateDataMobileSearchClick';

