export enum CUSTOMER_SERVICES_ENUMS {
  UNUS = 1,
  TEXT_LIVE_CHAT,
  TAWK
}

export const CUSTOMER_SERVICES_STRING_KEYS: Record<CUSTOMER_SERVICES_ENUMS, string> = {
  [CUSTOMER_SERVICES_ENUMS.UNUS]: "Unus Live Chat",
  [CUSTOMER_SERVICES_ENUMS.TEXT_LIVE_CHAT]: "textLiveChat",
  [CUSTOMER_SERVICES_ENUMS.TAWK]: "tawk"
}
