export enum GAME_TYPE_ENUMS {
  /** 老虎機 */
  SLOT = 1,
  /** 真人 */
  LIVECASINO = 2,
  /** 體育 */
  SPORTBOOK = 3,
  /** 虛擬體育 */
  VIRTUALSPORT = 4,
  /** 彩票 */
  LOTTERY = 5,
  /** 卡牌 */
  CARDBOARD = 6,
  /** 對戰 */
  P2P = 7,
  // 捕魚
  FISHING = 8,
  // 其他
  OTHER = 9,
  // 鬥雞
  COCKFIGHTING = 10,
  // 電競
  ESPORT = 11,
  // 撲克
  POKER = 12,
  // 至尊賭場
  CASINO_PREMIUM = 13
}

export const GAME_TYPE_I18N_KEYS: Record<GAME_TYPE_ENUMS, string> = {
  [GAME_TYPE_ENUMS.SLOT]: "menu.slots",
  [GAME_TYPE_ENUMS.LIVECASINO]: "menu.live_casino",
  [GAME_TYPE_ENUMS.SPORTBOOK]: "menu.sports",
  [GAME_TYPE_ENUMS.VIRTUALSPORT]: "menu.virtualSport",
  [GAME_TYPE_ENUMS.LOTTERY]: "menu.lottery",
  [GAME_TYPE_ENUMS.CARDBOARD]: "menu.cardboard",
  [GAME_TYPE_ENUMS.P2P]: "menu.p2p",
  [GAME_TYPE_ENUMS.FISHING]: "menu.fishing",
  [GAME_TYPE_ENUMS.OTHER]: "menu.other",
  [GAME_TYPE_ENUMS.COCKFIGHTING]: "menu.cockfighting",
  [GAME_TYPE_ENUMS.ESPORT]: "menu.esport",
  [GAME_TYPE_ENUMS.POKER]: "menu.poker",
  [GAME_TYPE_ENUMS.CASINO_PREMIUM]: "menu.casino_premium"
}

export const FrontendKey: Record<GAME_TYPE_ENUMS, string> = {
  [GAME_TYPE_ENUMS.SLOT]: "slots",
  [GAME_TYPE_ENUMS.LIVECASINO]: "casino",
  [GAME_TYPE_ENUMS.SPORTBOOK]: "sports",
  [GAME_TYPE_ENUMS.VIRTUALSPORT]: "vsport",
  [GAME_TYPE_ENUMS.LOTTERY]: "lottery",
  [GAME_TYPE_ENUMS.CARDBOARD]: "cardboard",
  [GAME_TYPE_ENUMS.P2P]: "p2p",
  [GAME_TYPE_ENUMS.FISHING]: "fishing",
  [GAME_TYPE_ENUMS.OTHER]: "other",
  [GAME_TYPE_ENUMS.COCKFIGHTING]: "cockfighting",
  [GAME_TYPE_ENUMS.ESPORT]: "esport",
  [GAME_TYPE_ENUMS.POKER]: "poker",
  [GAME_TYPE_ENUMS.CASINO_PREMIUM]: "casino_premium"
}

/**
 * 1.大廳開啟遊戲
 * 2.遊戲入口開啟遊戲
 */
export enum CATEGORY_ENUMS {
  LOBBYOPEN = 1,
  GAMEOPEN
}

export const Category: Record<GAME_TYPE_ENUMS, number> = {
  [GAME_TYPE_ENUMS.SLOT]: CATEGORY_ENUMS.GAMEOPEN,
  [GAME_TYPE_ENUMS.LIVECASINO]: CATEGORY_ENUMS.LOBBYOPEN,
  [GAME_TYPE_ENUMS.SPORTBOOK]: CATEGORY_ENUMS.LOBBYOPEN,
  [GAME_TYPE_ENUMS.VIRTUALSPORT]: CATEGORY_ENUMS.LOBBYOPEN,
  [GAME_TYPE_ENUMS.LOTTERY]: CATEGORY_ENUMS.LOBBYOPEN,
  [GAME_TYPE_ENUMS.CARDBOARD]: CATEGORY_ENUMS.LOBBYOPEN,
  [GAME_TYPE_ENUMS.P2P]: CATEGORY_ENUMS.GAMEOPEN,
  [GAME_TYPE_ENUMS.FISHING]: CATEGORY_ENUMS.GAMEOPEN,
  [GAME_TYPE_ENUMS.OTHER]: CATEGORY_ENUMS.GAMEOPEN,
  [GAME_TYPE_ENUMS.COCKFIGHTING]: CATEGORY_ENUMS.LOBBYOPEN,
  [GAME_TYPE_ENUMS.ESPORT]: CATEGORY_ENUMS.LOBBYOPEN,
  [GAME_TYPE_ENUMS.POKER]: CATEGORY_ENUMS.GAMEOPEN,
  [GAME_TYPE_ENUMS.CASINO_PREMIUM]: CATEGORY_ENUMS.LOBBYOPEN
}

/** Maps the string name of a game type (as returned by the product API) to its numeric GAME_TYPE_ENUMS value. */
export const GAME_TYPE_STRING_TO_ENUMS: Record<string, GAME_TYPE_ENUMS> = {
  SLOT: GAME_TYPE_ENUMS.SLOT,
  LIVECASINO: GAME_TYPE_ENUMS.LIVECASINO,
  SPORTBOOK: GAME_TYPE_ENUMS.SPORTBOOK,
  VIRTUALSPORT: GAME_TYPE_ENUMS.VIRTUALSPORT,
  LOTTERY: GAME_TYPE_ENUMS.LOTTERY,
  CARDBOARD: GAME_TYPE_ENUMS.CARDBOARD,
  P2P: GAME_TYPE_ENUMS.P2P,
  FISHING: GAME_TYPE_ENUMS.FISHING,
  OTHER: GAME_TYPE_ENUMS.OTHER,
  COCKFIGHTING: GAME_TYPE_ENUMS.COCKFIGHTING,
  ESPORT: GAME_TYPE_ENUMS.ESPORT,
  POKER: GAME_TYPE_ENUMS.POKER,
  CASINO_PREMIUM: GAME_TYPE_ENUMS.CASINO_PREMIUM
}
