export enum KYC_VERIFIED_ENUMS {
  VERIFICATION_STATUS_NOT_STARTED = 0, // 未開始
  VERIFICATION_STATUS_VERIFIED = 1, // 已驗證
  VERIFICATION_STATUS_REJECTED = 2, // 驗證被拒
  VERIFICATION_STATUS_EXPIRED = 3, // 驗證過期
  VERIFICATION_STATUS_PENDING = 4, // 待驗證
  VERIFICATION_STATUS_PROCESSING = 5 // 驗證中
}

export const KYC_VERIFIED_I18N_KEYS: Record<KYC_VERIFIED_ENUMS, string> = {
  /** 未定義(全部) */
  [KYC_VERIFIED_ENUMS.VERIFICATION_STATUS_NOT_STARTED]: "process_status.unStarted",
  [KYC_VERIFIED_ENUMS.VERIFICATION_STATUS_VERIFIED]: "process_status.approved",
  [KYC_VERIFIED_ENUMS.VERIFICATION_STATUS_REJECTED]: "process_status.rejected",
  [KYC_VERIFIED_ENUMS.VERIFICATION_STATUS_EXPIRED]: "process_status.expired",
  [KYC_VERIFIED_ENUMS.VERIFICATION_STATUS_PENDING]: "process_status.pendings",
  [KYC_VERIFIED_ENUMS.VERIFICATION_STATUS_PROCESSING]: "process_status.processing"
}
