export enum REPORT_DATE_TYPES_ENUMS {
  /** 7天內 */
  LASTSEVENDAYS = 1,

  /** 14天內 */
  LASTFOURTEENDAYS  = 2,

  /** 30天內 */
  LASTTHIRTYDAYS = 3,

  /** 自定日期 */
  CUSTOMDATE = 4,

  /** 今天 */
  TODAY = 5,

  /** 昨天 */
  YESTERDAY = 6
}

export const REPORT_DATE_TYPES_I18N_KEYS: Record<REPORT_DATE_TYPES_ENUMS, string> = {
  [REPORT_DATE_TYPES_ENUMS.LASTSEVENDAYS]: "common.btn.withinSevenDays",
  [REPORT_DATE_TYPES_ENUMS.LASTFOURTEENDAYS]: "common.btn.withinFourteenDays",
  [REPORT_DATE_TYPES_ENUMS.LASTTHIRTYDAYS]: "common.btn.withinThirtyDays",
  [REPORT_DATE_TYPES_ENUMS.CUSTOMDATE]: "common.btn.customDate",
  [REPORT_DATE_TYPES_ENUMS.TODAY]: "common.btn.today",
  [REPORT_DATE_TYPES_ENUMS.YESTERDAY]: "common.btn.yesterday"
}

export const REPORT_DATE_TYPES_SUBTRACT_DAYS: Record<REPORT_DATE_TYPES_ENUMS, number> = {
  [REPORT_DATE_TYPES_ENUMS.LASTSEVENDAYS]: -7,
  [REPORT_DATE_TYPES_ENUMS.LASTFOURTEENDAYS]: -14,
  [REPORT_DATE_TYPES_ENUMS.LASTTHIRTYDAYS]: -30,
  [REPORT_DATE_TYPES_ENUMS.CUSTOMDATE]: 0,
  [REPORT_DATE_TYPES_ENUMS.TODAY]: 0,
  [REPORT_DATE_TYPES_ENUMS.YESTERDAY]: 0
}
