export const t = {
//   for PrivacyAgreementPage
    title: `Política de Privacidade`,
    policy_1_title: `1. Introduction:`,
    policy_1_content: (data: string) => `At ${data}, we aim to provide the best possible experience to Users. Therefore, in order for us to provide an increasingly personalized service for you, our Users, we need to understand your gaming and interaction habits. However, the privacy and security of your personal data has always been of paramount concern to us. That is why we wish to explain, in a transparent and detailed fashion, how we collect, store, share and use personal data from Users, as well as detail the choices and control options you shall have at your disposal when and if you decide to share said personal data. This is the main purpose of this Privacy and Personal Data Protection Policy ("Policy").`,
    policy_2_title: `2. About this Policy`,
    policy_2_content_1: (data: string) => `This Policy determines the key details of the relationship between Users personal data and ${data}. The Policy applies to all ${data} services as well as any associated services (hereinafter referred to as " ${data} services"). The terms governing the use of the ${data} services by Users are defined in our Terms and Conditions of Use.`,
    policy_2_content_2: `From time to time, we may develop new services or offer additional services. If the introduction of these new or additional services results in any changes in how we collect and handle Users personal data, we shall provide more information and additional terms or policies. Unless otherwise stated, whenever we introduce new or additional services, these shall be subject to this Policy.`,
    policy_3_content_1: `The purposes of this Policy are:`,
    policy_3_content_2: `Ensure that Users understand exactly what personal data we collect about them, the reasons why we collect and use such data and with whom we share these;`,
    policy_3_content_3: (data: string) => `Explain how we use the personal data Users share with us, in order to provide you with a great experience whenever you use ${data} services; and`,
    policy_3_content_4: `Explain to Users their respective rights and choices regarding the personal data we collect and process, as well as how we protect their privacy.`,
    policy_3_content_5: `We expect that this Policy helps Users understand our commitment to their privacy. For information on how to contact us in case you have any questions on concerns, please refer to section 14 "Contacting us" below.`,
    policy_3_content_6: (data: string) => `On the other hand, if a User does not agree with the content of this Policy, we hereby declare that users are free to decide whether to use and/or continue using ${data} services.`,

    policy_4_content_1: `User rights and preferences: providing you with choices and control options:`,
    policy_4_content_2: `If you do not already know, there are European Union and Brazilian laws, the General Data Protection Regulation (or "GDPR") and the Brazilian General Personal Data Protection Law (or "LGDP"), respectively, which grant certain rights to individuals in relation to their personal data. As provided for under the applicable laws and except for any limitations found therein, the rights granted to individuals are as follows:`,
    policy_4_content_3: `Right to access - the right to be informed and request access to the personal data we process about the User;`,
    policy_4_content_4: `Right to rectification - the right to request that we change or update the User's personal data whenever these are incorrect or incomplete;`,
    policy_4_content_5: `Right to information erasure - the right to request us to delete your personal data from our database;`,
    policy_4_content_6: `Right to restriction - the right to request that we, either temporarily or permanently, stop processing all or some of your personal data;`,
    policy_4_content_7: `Right to objection - the right to, at any given time, object to the processing of your personal data for reasons related to your particular situation; the right to object to your personal data being processed for direct marketing purposes;`,
    policy_4_content_8: `Right to data portability - the right to request a copy of your personal data in electronic form and the right to transmit such personal data for use in third-party services;`,
    policy_4_content_9: `Right to not be subject to automated decisions - the right not to be subject to a decision based solely on an automated decision with respect to personal data, including profiling, in cases where the decision may have a legal effect for you or have an equally significant effect.`,


    policy_5_content_1: (data: string) => `In order for Users to be able to easily exercise these rights and record their preferences regarding how ${data} uses their personal data, we provide the following options`,
    policy_5_content_2: `1.Control some of the categories of personal data we handle;`,
    policy_5_content_3: `2.Manage your publicly available personal data;`,
    policy_5_content_4: `3.Set sharing preferences.`,
    policy_5_content_5: `If we send you electronic marketing messages based on your consent or as otherwise permitted by applicable law, Users may at any time, respectively, withdraw their authorization or state their objection ("refusal") without any additional charges. To do so, all they have to do is use the link found in the electronic message itself to unsubscribe from the mailing list.`,
    policy_5_content_6: `In case of questions regarding their privacy, rights, or how to exercise such rights, Users should contact our data protection officer through our Telegram customer service. We shall issue a reply within a reasonable period of time after verifying the identity of the User in question.`,
    policy_5_content_7: `If you are unhappy with how we are using your personal data, you may also file a written complaint with the Data Protection Authority in your local jurisdiction.`,
    policy_5_content_8: `4. How do we collect personal data from Users?`,
    policy_5_content_9: `We collect personal data from Users in the following ways:`,
    policy_5_content_10: (data: string) => `When Users registers with a ${data} service: upon registration, we collect certain personal data, such as, but not limited to: email address, full name, sex, country, IP address, access device and its identifier so that they can use the ${data} service in question.`,
    policy_5_content_11: (data: string) => `Through the use of a ${data} service: when User use a ${data} service, we collect personal data about their use of the ${data} service in question, such as games played, history of plays, list of devices used to access the services, nicknames that accessed the services from a single device, variation of ranking positions, variation in the balance of virtual credits for each User, IP addresses used for access, among other information deemed necessary to achieve our corporate goals. From time to time, Users may also provide us with additional personal data or grant us permission to collect additional personal data in order to provide you with more features or functionalities, for instance. The personal data collected also allows us to mitigate risks and/or frauds regarding users and against the services.`,
    policy_5_content_12: (data: string) => `Through third parties - we may also receive personal data in connection with Users and their activities from third parties, including advertisers and partners we work with, so that we may provide ${data} services (please refer to Section 7 "Sharing Users personal data" below). We shall use these personal data if the User in question authorized the relevant third party, or ${data}, to share such data, or if ${data} has a legitimate interest in using these personal data to provide a ${data} service to the User.`,
    policy_5_content_13: (data: string) => `Through third parties - we may also receive personal data in connection with Users and their activities from third parties, including advertisers and partners we work with, so that we may provide ${data} services (please refer to Section 7 "Sharing Users personal data" below). We shall use these personal data if the User in question authorized the relevant third party, or ${data}, to share such data, or if ${data} has a legitimate interest in using these personal data to provide a ${data} service to the User.`,
    policy_5_content_14: `As described below, we do not collect photographs, exact geographic locations obtained from mobile devices, voice data or contact lists from Users without their previous authorization. You can always change your mind and withdraw your consent at any time.`,
    policy_5_content_15: `5. What kind of personal data about Users do we collect?`,


    policy_5_content_16: `In the tables below, we organize the categories of Users personal data that we collect and use:`,
    policy_5_content_17: `Personal data categories Category description`,
    policy_5_content_18: `Account registration information`,
    policy_5_content_19: (data: string) => `These are the personal data provided by Users or data that we collect so that Users may use a ${data} service. These include name, surname, ID, email address, date of birth, sex and physical address of Users.`,
    policy_5_content_20: `Some personal data requested are mandatory for Users to create their account. Users also have the option of providing us with some additional personal data so that their experience is more personalized.`,
    policy_5_content_21: (data: string) => `The specific personal data we collect depends on how the ${data} services are used by Users and whether they use a third party service (as defined in the Terms and Conditions of Use), such as Facebook, to use ${data} services. If a User uses a third party service to create an account, we shall receive personal data through such third party service, but only if the User has authorized the third party service in question to share their personal data with us.`,
    policy_5_content_22: `Usage data`,
    policy_5_content_23: (data: string) => `These are the personal data collected about Users when they use a ${data} service, which may include:`,
    policy_5_content_24: (data: string) => `Information about the kind of ${data} service plan.`,
    policy_5_content_25: (data: string) => `Information on User interactions with the ${data} services, such as games played, history of plays, list of devices used to access the services, history of nicknames used to access the services from a single device, variation of ranking positions and variation in the balance of virtual credits for each User, in addition to their interactions with other ${data} Users.`,
    policy_5_content_26: `These may also include information about the use of third-party applications and any advertisements you receive.`,
    policy_5_content_27: (data: string) => `User content (as defined in the Terms and Conditions of Use of the services) they publish on ${data}, including the messages they send and/or receive through ${data} and their interactions with the ${data} Customer Support team.`,
    policy_5_content_28: (data: string) => `Technical data, which may include URL information, cookie data, IP address of the User, the devices used to access ${data} services, exclusive device identifications, device attributes and type of network connection (Wi-Fi, 3G, LTE, Bluetooth etc.), as well as network provider, network and device performance, browser, language, information that allows for the management of digital rights, operating system and ${data} application version.`,
    policy_5_content_29: `Personal data collected with your authorization that allow us to provide you with additional functions or functionalities:`,
    policy_5_content_30: `Personal data categories Category description`,
    policy_5_content_31: `Optional mobile data`,
    policy_5_content_32: (data: string) => `In addition to the mobile data we collect to provide Users with the ${data} services (described above), Users also have the option to authorize us to collect additional personal data from their mobile devices so that we can provide them with features and functionalities that shall enhance their experience regarding ${data} services.`,
    policy_5_content_33: `We shall not collect any of the personal data listed below without first obtaining User consent:`,
    policy_5_content_34: `Users photographs - If a User gives us permission to access their photographs or their camera, we shall only collect the images they specifically choose to share with us and the metadata related to such images, such as file type and image size. We shall never scan or import a Users photo library or camera roll;`,
    policy_5_content_35: (data: string) => `Exact geographic location obtained from Users mobile devices - If Users authorizes us to access specific geographic locations, this shall allow us to use Users GPS or Bluetooth in order to provide ${data} service functionalities that require exact geographic location. Please note that this does not include Users IP address. We use Users IP address to determine non-exact geographic location, such as in which country they are located, in order to comply with the purpose of our Terms and Conditions of Use;`,
    policy_5_content_36: (data: string) => `Exact geographic location obtained from Users mobile devices - If Users authorizes us to access specific geographic locations, this shall allow us to use Users GPS or Bluetooth in order to provide ${data} service functionalities that require exact geographic location. Please note that this does not include Users IP address. We use Users IP address to determine non-exact geographic location, such as in which country they are located, in order to comply with the purpose of our Terms and Conditions of Use;`,
    policy_5_content_37: (data: string) => `Users contact list - If a User gives us authorization to access their contact list, we can consult the list of contacts stored on their device in order to help such User to find friends who use ${data}`,
    policy_5_content_38: `Payment information`,
    policy_5_content_39: (data: string) => `We may collect this personal data if a User registers for a Trial Period or makes any purchase through a ${data} service (as defined in the Terms and Conditions of Use). The actual personal data collected may vary depending on the payment method, but may include information such as:`,
    policy_5_content_40: `Name;`,
    policy_5_content_41: `Date of birth`,
    policy_5_content_42: `ID`,
    policy_5_content_43: `Type of debit or credit card, expiration date and certain card number digits;`,
    policy_5_content_44: `Physical address;`,
    policy_5_content_45: `Phone number;`,
    policy_5_content_46: `Users transaction history information;`,
    policy_5_content_47: `If a User chooses to pay by invoice, we shall provide their personal data to our payment processors so that they may carry out credit checks and send invoices to the User.`,
    policy_5_content_48: `Special offers, contests and sweepstakes`,
    policy_5_content_49: `These personal data are used to enable Users to register and participate in special offers. `,
    policy_5_content_50: `Specific personal data collected may vary, depending on the special offer.`,
    policy_5_content_51: `Marketing data`,
    policy_5_content_52: (data: string) => `These personal data are used to allow ${data} and its partners/service providers to send marketing communications to Users:`,
    policy_5_content_53: `by email`,
    policy_5_content_54: (data: string) => `while using the ${data} service`,
    policy_5_content_55: `directly from a third party.`,
    policy_5_content_56: `6. For what purposes do we use personal data from Users?`,
    policy_5_content_57: (data: string) => `When Users use or interact with ${data} services, we use various technologies to process the personal data collected about Users for various reasons. In the table below, we set out the reasons why we process Users personal data, the associated legal grounds on which our actions are based and which allow us to legally process Users personal data and the categories of personal data (identified in section 5 "What kind of personal data about Users do we collect?") used for these purposes:`,
    policy_5_content_58: (data: string) => `Indication of the reason why ${data} handles Users personal data ("processing purposes") Legal grounds for processing purposes Categories of personal data used by ${data} for processing purposes`,
    policy_5_content_59: (data: string) => `In order to provide, customize and improve User experience with regard to ${data} services as well as other services and products provided by ${data}, such as when providing content that is personalized, individualized or adjusted according to User location, as well as recommendations, features and advertisements inside or outside ${data} (including third-party products and services).`,
    policy_5_content_60: `Celebration of an agreement`,
    policy_5_content_61: `Legitimate interests`,
    policy_5_content_62: `Account registration data`,
    policy_5_content_63: `Service use data`,
    policy_5_content_64: `Optional mobile data, if necessary`,
    policy_5_content_65: (data: string) => `In order to ensure the integrity of the rankings for the modalities offered, the ${data} entertainment environment and mitigate actions related to fraud and collusion between Users.`,
    policy_5_content_66: `Celebration of an agreement`,
    policy_5_content_67: `Legitimate interests`,
    policy_5_content_68: `Account registration data`,
    policy_5_content_69: `Service use data`,
    policy_5_content_70: (data: string) => `In order to understand how Users access and use ${data} services, aiming at ensuring the technical functionality of the ${data} services, develop new products and services and analyze the use of ${data} services by Users, including its interaction with applications, advertisements, products and services that are made available, associated with, or offered by way of ${data}`,
    policy_5_content_71: `Celebration of an agreement`,
    policy_5_content_72: `Legitimate interests`,
    policy_5_content_73: `Account registration data`,
    policy_5_content_74: `Service use data`,
    policy_5_content_75: (data: string) => `In order to establish communication with Users for purposes related to the ${data} services.`,
    policy_5_content_76: `Celebration of an agreement`,
    policy_5_content_77: `Legitimate interests`,
    policy_5_content_78: `Account registration data`,
    policy_5_content_79: `Service use data`,
    policy_5_content_80: (data: string) => `In order to process Users payments and prevent or identify frauds, including fraudulent payments and fraudulent use of the ${data} services.`,
    policy_5_content_81: `Celebration of an agreement`,
    policy_5_content_82: `Fulfillment of legal obligations`,
    policy_5_content_83: `Legitimate interests`,
    policy_5_content_84: `Account registration data`,
    policy_5_content_85: `Service use data`,
    policy_5_content_86: `Payment information`,
    policy_5_content_87: `In order to establish communication with Users, either directly or through our partners, for the following purposes:`,
    policy_5_content_88: `marketing`,
    policy_5_content_89: `surveys`,
    policy_5_content_90: `participation in contests and special offers`,
    policy_5_content_91: (data: string) => `through emails, notifications or other messages, in accordance with any authorizations that may have been transmitted by Users to ${data} (through the Privacy settings, for instance).`,
    policy_5_content_92: `Authorization`,
    policy_5_content_93: `Legitimate interests`,
    policy_5_content_94: `Contest and sweepstakes data`,
    policy_5_content_95: `Marketing data`,
    policy_5_content_96: `In order to provide Users with functionalities, information, advertisements or content based on Users exact location.`,
    policy_5_content_97: `Authorization`,
    policy_5_content_98: `Optional mobile data`,
    policy_5_content_99: (data: string) => `We use anonymized and aggregated information for purposes that include testing our IT systems, researching, analyzing data, creating marketing and promotion models, improving ${data} services and developing new features and functionalities for ${data} services.`,
    policy_5_content_100: `7. Sharing Users personal data:`,
    policy_5_content_101: (data: string) => `We list below the categories of the recipients of personal data that have been collected or generated through the use of the ${data} service by Users, as applicable:`,
    policy_5_content_102: `Publicly available information`,
    policy_5_content_103: (data: string) => `The following personal data from Users shall always be publicly available on the ${data} service: Users nickname, profile picture, game performance information and account creation date, among other personal data that can be verified on the Users Profile page.`,
    policy_5_content_104: `Personal data that Users may choose to share`,
    policy_5_content_105: `The following personal data shall only be shared with the recipient categories indicated in the table below if:`,
    policy_5_content_106: (data: string) => `Users choose a specific functionality of the ${data} service for which the sharing of personal data is necessary for the appropriate use of the functionality of the ${data} service;`,
    policy_5_content_107: (data: string) => `Users explicitly authorize the sharing of personal data, for instance, by selecting the appropriate setting in the Privacy settings of the ${data} service.`,
    policy_5_content_108: `Recipient categories Reason for sharing`,
    policy_5_content_109: (data: string) => `Third-party application used by Users to log into ${data} When accessing their ${data} account from a third-party application, such as social media applications, ${data} may share their data so that Users are linked in both registers, that is, the ${data} network and any third party;`,
    policy_5_content_110: (data: string) => `If a User associates a third-party application using their ${data} account credentials, then such third-party application may have access to certain service use data, stored content and activities. Before connecting to the Third Party Application, the User shall receive a notice stating that their personal data shall be shared with/may be accessed by such Third Party Application.`,
    policy_5_content_111: (data: string) => `Community When a User joins the ${data} Community, they shall use the same nickname as the one from their account. Such User nickname shall be publicly displayed to anyone who also accesses the ${data} Community area, along with any questions, comments and other content that they can post or make public through the ${data} service's Privacy settings.`,
    policy_5_content_112: `More details on publicly available information and on what Users share with third parties are available in Section 3, "User rights and preferences: providing you with choices and control options", of this Policy and the Privacy settings.`,
    policy_5_content_113: `Information we may share`,
    policy_5_content_114: `Recipient categories Reason for sharing`,
    policy_5_content_115: `Service providers and other parties`,
    policy_5_content_116: (data: string) => `We use technical service providers that operate the technical infrastructure we need to provide the Slots Big Boss Services, in particular providers that host, store, manage and maintain the ${data} application, its content and the data we process.`,
    policy_5_content_117: `We use technical service providers to help us communicate with Users as described in Section 6 of this Policy.`,
    policy_5_content_118: (data: string) => `We use marketing and advertising partners to show more personalized content or to help us understand how Users use the ${data} services and provide them with better service. We may also share personal data with certain marketing and advertising partners in order to send Users promotional communications about ${data}`,
    policy_5_content_119: `Additionally, we use payment partners; however, in this case we do not store or share credit card data or other payment methods, and all data with regard to payments that are entered on our pages are encrypted and sent to the respective payment APIs.`,
    policy_5_content_120: (data: string) => `${data} Partners`,
    policy_5_content_121: (data: string) => `Should Users access the ${data} service through an offer that they have received or acquired through a third party, such as their mobile network operator, we shall share personal data with such third party about their use of the ${data} service, such as if and to what extent they used the offer, if they activated a Slots Big Boss account or whether they have actively used the ${data} service.`,
    policy_5_content_122: `We also share Users personal data in a pseudonymous format with marketing partners that help us in promotional efforts and with advertisers that allow us to offer a free service.`,
    policy_5_content_123: `Compliance with the law and data protection authorities`,
    policy_5_content_124: `We shall share Users personal data when we believe, in good faith, that this is necessary in order to fulfill a legal obligation under the applicable law, or to respond to a valid legal proceeding, such as a search warrant, a court order or a subpoena.`,
    policy_5_content_125: `We shall also share Users personal data if we believe, in good faith, this is necessary for our legitimate interest, or the interest of third parties, as well as in terms of matters of national security, law enforcement, litigation, criminal investigation, protecting anyone's safety, or to prevent death or imminent physical harm, provided that we take into account the fact that such interest does not prevail over the interests or fundamental rights and freedoms of Users that require the protection of Users personal data.`,
    policy_5_content_126: `Buyers of our business.`,
    policy_5_content_127: `We shall share Users personal data when we sell or negotiate the sale of our business to a buyer or potential buyer.`,
    policy_5_content_128: (data: string) => `In this case, ${data} shall continue to ensure the confidentiality of Users personal data and we shall notify them before their personal data is transferred to the buyer or is subject to a different Privacy Policy.`,
    policy_5_content_129: `8. Data conservation and erasure:`,
    policy_5_content_130: (data: string) => `We retain Users personal data for as long as necessary in order to provide the ${data} service and for legitimate and essential business purposes, such as to maintain the performance of the ${data} service, make business decisions about functionalities and offers based on data, fulfill our legal obligations, and resolve disputes. We retain some of the personal data obtained from Users while they remain Users of the ${data} service. For instance, we keep User history and their purchase history, profile, ranking positions, credit history and other account information.`,
    policy_5_content_131: `At the Users request, we shall erase or anonymize their personal data so that they do not allow for User identification, unless it is legally permitted or mandatory to keep certain personal data during processing, including situations such as the following:`,
    policy_5_content_132: `If there is an unresolved issue with a Users account, such as an outstanding credit to their account or an unresolved complaint or dispute, we shall retain all the necessary personal data until the issue is resolved;`,
    policy_5_content_133: `If we are required to retain personal data in order to comply with our legal, tax, auditing and accounting obligations, we shall retain all the necessary personal data for the period required by applicable law;`,
    policy_5_content_134: `Whenever deemed necessary for our legitimate business interests, such as fraud prevention or to maintain the security of our Users.`,
    policy_5_content_135: `9. Transfer to other countries:`,
    policy_5_content_136: (data: string) => `${data} shares some personal data obtained from Users on a global level with the company UNITED JOY LLP, headquartered in the city of London - UK, in order to carry out the activities specified in this Policy.`,
    policy_5_content_137: (data: string) => `${data} may also subcontract processing services or share the personal data obtained from Users with third parties located in countries other than their country of residence. The personal data obtained from Users may, therefore, be subject to privacy laws different from those in force in their country of residence.`,
    policy_5_content_138: (data: string) => `Personal data collected in the European Union and Switzerland may, for instance, be transferred and processed by third parties located in a country outside the European Union and Switzerland. In these cases, ${data} shall ensure that the transfer of Users personal data is carried out in accordance with the applicable privacy laws, as well as ensure, in particular, the adoption of the appropriate contractual, technical and organizational measures, such as the standard contractual clauses approved by the European Commission.`,
    policy_5_content_139: `More information about the security measures we use to protect Users personal data is available in Section 11, "Keeping Users personal data safe”.`,
    policy_5_content_140: `10. URLs:`,
    policy_5_content_141: `We may exhibit third-party advertisements and other content such as URLs redirecting to third-party websites. We cannot control, nor may we be held responsible for, the privacy practices and content by third parties. If a User clicks on an advertisement or a third-party URL, they should be aware that they are exiting the Slots Big Boss service and that any personal data they provide shall not be covered by this Policy. Users should read the respective privacy policies in order to find out how they collect and process their personal data.`,
    policy_5_content_142: `11. Keeping Users personal data safe:`,
    policy_5_content_143: `We are committed to protecting the personal data of our Users.`,
    policy_5_content_144: `We implement technical and organizational measures to help protect the security of the personal data obtained from our Users, namely: creation of nicknames, encryption and access and retention policies to prevent unauthorized access and unnecessary retention of personal data in our systems. However, Users must be made aware of the fact that no system is completely secure.`,
    policy_5_content_145: (data: string) => `A password protects User accounts, and that is why we encourage Users to use a unique and robust password, to limit access to computers, browse rs and other devices deemed secure (trusted), and to log out after using the ${data} service.`,
    policy_5_content_146: `12. Children:`,
    policy_5_content_147: `Children Between Age of 13 and 18`,
    policy_5_content_148: `We recommend that minors over the age of 13 ask their parents for permission before sending any information about themselves to anyone over the Internet.`,
    policy_5_content_149: `1.User shall use his/her account only for non-commercial entertainment purposes.`,
    policy_5_content_150: `2.User shall not use the service for any other purpose, such as collecting chips from various accounts or by any other means.`,
    policy_5_content_151: `3.User shall not use his/her account for any illegal activity.`,
    policy_5_content_152: `4.User shall not use his/her account to transmit repetitive messages (spam), junk e-mail, advertise and solicit.`,
    policy_5_content_153: `5.User shall not use profanity or language that discriminates or maliciously targets another individual in any way. This includes his/her profile picture.`,
    policy_5_content_154: `6.User shall not use his/her account to cheat or hack the game by any means. Losing on purpose as a means of transferring chips can be tracked easily, and this behavior will have his/her chips taken and banned.`,
    policy_5_content_155: (data: string) => `7.User shall not sublicense, lease, trade, gift, sell or otherwise transfer his/her account or associated virtual items partly or fully to anyone without written permission from ${data}`,
    policy_5_content_156: `8.User shall not buy or get chips, bonus and any other virtual items from any unauthorized source such as links from unknown sources or people promising free chips, etc.`,
    policy_5_content_157: `9.User are allowed one account per social network to use the service. In addition, User cannot use multiple accounts to try to accumulate free chips. This behavior is easily detectible and will result in all your accounts being suspended and/or banned.`,
    policy_5_content_158: `10.User shall not use scripts and manual processes to abusively accumulate free chips.`,
    policy_5_content_159: `11.User shall not use any of the services or create an account or use an account if Users have been removed or banned from using the service.`,
    policy_5_content_160: (data: string) => `12.User shall not use any of the ${data} game or service if you do not agree with the terms of service and User license to use the service shall immediately terminate.`,
    policy_5_content_161: `13.User have no right to carry out actions including but not limited to:`,
    policy_5_content_162: (data: string) => `Deleting all the information and contents related the copyright on ${data} software and other copies; Performing reverse engineering, reverse assembly, reverse compilation, etc., to the game of the ${data}, regardless of any purpose of plagiarizing or changing the game software of ${data}; For information related to the software of game of the ${data} (without the written consent of ${data}) you cannot (without authorization including but not limited to) use, copy, modify, link, reprint, assemble, release, publish, set up a mirror site, or use ${data} game for these purposes without authorization to develop derivative products, works or services related to the software.`,
    policy_5_content_163: `13. Changes to this Privacy Policy:`,
    policy_5_content_164: `From time to time, we may make changes to this Policy.`,
    policy_5_content_165: (data: string) => `When we make material changes to this Policy, we shall draw up a notable and appropriate communication, depending on the circumstances, by exhibiting, for instance, a notable communication on the ${data} service or by sending an email message to Users. We may send a communication to Users in advance.`,
    policy_5_content_166: `Therefore, it is essential that Users read all communications carefully.`,
    policy_5_content_167: `14. Contacting us:`,
    policy_5_content_168: `Thank you for reviewing our Privacy Policy. If you have any questions regarding this Policy, please reach out to our Data Protection Officer via our Telegram customer service. We shall issue a reply within a reasonable period of time after verifying the identity of the User in question.`,
    policy_5_content_169: (data: string) => `${data} is responsible for the processing data for the purposes of the personal data obtained from Users processed under this Policy.`,

}

export default t;