import { MAYA_ERROR_CODE_TYPE } from "@shared-lib/constants/enums/mayaErrorCodeType"

export const genMayaErrorMsg = (
  options: {
    excode: MAYA_ERROR_CODE_TYPE
  } = {
    excode: MAYA_ERROR_CODE_TYPE.Unknow
  },
  t: (key: string, ...args: any[]) => string
): string => {
  if (!options.excode) {
    return `excode is not exist.`
  }

  switch (options.excode) {
    case MAYA_ERROR_CODE_TYPE.RECIPIENT_ACCOUNT_RESTRICTED:
      return `${t("maya_error_message.RECIPIENT_ACCOUNT_RESTRICTED")}`
    case MAYA_ERROR_CODE_TYPE.TRANSFER_TO_SAME_ACCOUNT_NOT_ALLOWED:
      return `${t("maya_error_message.TRANSFER_TO_SAME_ACCOUNT_NOT_ALLOWED")}`
    case MAYA_ERROR_CODE_TYPE.INVALID_ACCOUNT_DETAILS:
      return `${t("maya_error_message.INVALID_ACCOUNT_DETAILS")}`
    case MAYA_ERROR_CODE_TYPE.RECIPIENT_PRIMARY_ACCOUNT_MARKED_AS_LOST:
      return `${t("maya_error_message.RECIPIENT_PRIMARY_ACCOUNT_MARKED_AS_LOST")}`
    case MAYA_ERROR_CODE_TYPE.RECIPIENT_PRIMARY_ACCOUNT_MARKED_AS_CARD_STOLEN:
      return `${t("maya_error_message.RECIPIENT_PRIMARY_ACCOUNT_MARKED_AS_CARD_STOLEN")}`
    case MAYA_ERROR_CODE_TYPE.INSUFFICIENT_FUNDS_TO_PROVIDE_TO_CUSTOMER:
      return `${t("maya_error_message.INSUFFICIENT_FUNDS_TO_PROVIDE_TO_CUSTOMER")}`
    case MAYA_ERROR_CODE_TYPE.RECIPIENT_PRIMARY_ACCOUNT_EXPIRED:
      return `${t("maya_error_message.RECIPIENT_PRIMARY_ACCOUNT_EXPIRED")}`
    case MAYA_ERROR_CODE_TYPE.RECEIVER_PERSONAL_INFO_NOT_ALLOWED_FOR_TRANSACTION_WITH_PARTNER:
      return `${t("maya_error_message.RECEIVER_PERSONAL_INFO_NOT_ALLOWED_FOR_TRANSACTION_WITH_PARTNER")}`
    case MAYA_ERROR_CODE_TYPE.RECIPIENT_REACHED_TOP_UP_LIMIT:
      return `${t("maya_error_message.RECIPIENT_REACHED_TOP_UP_LIMIT")}`
    case MAYA_ERROR_CODE_TYPE.RECIPIENT_REACHED_TOP_UP_LIMIT_COUNT:
      return `${t("maya_error_message.RECIPIENT_REACHED_TOP_UP_LIMIT_COUNT")}`
    case MAYA_ERROR_CODE_TYPE.PARTNER_ACCOUNT_REACHED_LIMIT:
      return `${t("maya_error_message.PARTNER_ACCOUNT_REACHED_LIMIT")}`
    case MAYA_ERROR_CODE_TYPE.RECIPIENT_PRIMARY_ACCOUNT_INVALID:
      return `${t("maya_error_message.RECIPIENT_PRIMARY_ACCOUNT_INVALID")}`
    case MAYA_ERROR_CODE_TYPE.AMOUNT_VALUE_MISMATCH1:
    case MAYA_ERROR_CODE_TYPE.AMOUNT_VALUE_MISMATCH2:
    case MAYA_ERROR_CODE_TYPE.AMOUNT_VALUE_MISMATCH3:
      return `${t("maya_error_message.AMOUNT_MISMATCH")}`
    case MAYA_ERROR_CODE_TYPE.RECIPIENT_INACTIVE_CANNOT_RECEIVE_FUNDS:
      return `${t("maya_error_message.RECIPIENT_INACTIVE_CANNOT_RECEIVE_FUNDS")}`
    case MAYA_ERROR_CODE_TYPE.RECIPIENT_FUNDS_CLOSED_CANNOT_RECEIVE:
      return `${t("maya_error_message.RECIPIENT_FUNDS_CLOSED_CANNOT_RECEIVE")}`

    case MAYA_ERROR_CODE_TYPE.INVALID_CLIENT_ID_HEADER:
    case MAYA_ERROR_CODE_TYPE.INVALID_PRODUCT_TYPE:
    case MAYA_ERROR_CODE_TYPE.RECIPIENT_TYPE_NOT_ALLOWED:
    case MAYA_ERROR_CODE_TYPE.INVALID_RECIPIENT_VALUE:
    case MAYA_ERROR_CODE_TYPE.RECIPIENT_NOT_VERIFIED_PAYMAYA_ACCOUNT:
    case MAYA_ERROR_CODE_TYPE.INTERNAL_SERVICE_TIMEOUT:
    case MAYA_ERROR_CODE_TYPE.INTERNAL_LEDGER_ERROR:
    case MAYA_ERROR_CODE_TYPE.INTERNAL_LEDGER_CATEGORY_ERROR:
    case MAYA_ERROR_CODE_TYPE.INTERNAL_LEDGER_CATEGORY_ERROR2:
    case MAYA_ERROR_CODE_TYPE.INTERNAL_LEDGER_CATEGORY_ERROR3:
    case MAYA_ERROR_CODE_TYPE.INTERNAL_LEDGER_CATEGORY_ERROR4:
    case MAYA_ERROR_CODE_TYPE.TEMPORARY_FAILURE:
    case MAYA_ERROR_CODE_TYPE.TRANSACTION_PENDING_OR_CONNECTION_FAILED:
    case MAYA_ERROR_CODE_TYPE.MOTHER_ACCOUNT_NOT_DEFINED_FOR_PARTNER:
    case MAYA_ERROR_CODE_TYPE.INVALID_MOTHER_ACCOUNT_PRODUCT_TYPE:
    case MAYA_ERROR_CODE_TYPE.INVALID_ADD_MONEY_CODE:
      return `${t("maya_error_message.ERROR_CODE_WITH_NUM", { code: options.excode })}`
    default:
      return `${t("maya_error_message.GATEWAY_OR_TIMEOUT_ERROR_CONTACT_SUPPORT")}`
  }
}
