
const reg = {}
reg.hmacSha256Sync = 'getPilauCode'
reg.setLandscape = 'setPilauScape'
reg.getLandscape = 'getPilauScape'
reg.setBadge = 'setPilauBadge'
reg.setStatusBarStyle = 'setPilauStyle'
reg.vibrate = 'viratePilau'
reg.getDeviceName = 'getPilauName'
reg.setVolume = 'setPilauVolume'
reg.getVolume = 'getPilauVolume'
reg.getSystemVolumSlider = 'getPilauSystemVolumSlider'
reg.setAudioCategory = 'setPilauCategory'
reg.download = 'download'
reg.updateUrl = 'updatePilauName'
reg.update = 'updatePilau'
reg.sgetItem = 'sgetPilauItem'
reg.ssetItem = 'ssetPilauItem'
reg.vgetItem = 'vgetPilauItem'
reg.vsetItem = 'vsetPilauItem'
reg.kgetItem = 'kgetPilauItem'
reg.ksetItem = 'ksetPilauItem'
reg.removeKeyItem = 'removePilauItem'
reg.check = 'checkPilau'
reg.open = 'openPilau'
reg.oiopen = 'oiopen'
reg.regist = 'registPilau'
reg.report = 'reportPilau'

export default reg
