const UNDEFINED_PARAMETER = 'UNDEFINED_PARAMETER:Do not pass an undefined parameter.';
const LOST_SCHEMA = 'EMPTY_SCHEMA" Some properpy in your schema is nto exist';
const RESOURCE_ERROR_MESSAGE_ID = 'RESOURCE_ERROR';
const VALIDATION_ERROR_MESSAGE_ID = 'Submission Section';
const TEMPLATE_ERROR_MESSAGE_ID = 'TEMPLATE_ERROR';
const SETUPENV_ERROR_MESSAGE_ID = 'SETUPENV_ERROR';

export {
  RESOURCE_ERROR_MESSAGE_ID,
  UNDEFINED_PARAMETER,
  LOST_SCHEMA,
  VALIDATION_ERROR_MESSAGE_ID,
  TEMPLATE_ERROR_MESSAGE_ID,
  SETUPENV_ERROR_MESSAGE_ID
};
