export const LOCAL_ICONS_MAPPING: Record<string, string[]> = {
  ['v6']: [
    'ic_hot_badge',
    'ic_new_badge',
    'ic_ranking_down',
    'ic_ranking_rise',

    'ic_mfg_smartsoft_default',
    'ic_mfg_fc_default',
    'ic_mfg_wickets_default',
    'ic_mfg_sexybcrt_default',
    'ic_mfg_toofun_default',
    'ic_mfg_lottery777_default',
    'ic_mfg_bng_default',
    'ic_mfg_pls_default',
    'ic_mfg_topbet_default',
    'ic_mfg_evolution_default',
    'ic_mfg_sw_default',
    'ic_mfg_qs_default',
    'ic_mfg_rg_default',
    'ic_mfg_pngo_default',
    'ic_mfg_wm_default',
    'ic_mfg_turbogames_default',
    'ic_mfg_spribe_default',
    'ic_mfg_pt_default',
    'ic_mfg_ot_default',
    'ic_mfg_ag_default',
    'ic_mfg_jili_default',
    'ic_mfg_pg_default',
    'ic_mfg_jdb_default',
    'ic_mfg_evort_default',
    'ic_mfg_evontt_default',
    'ic_mfg_cq9_default',
    'ic_mfg_wg_default',
    'ic_mfg_alize_default',
    'ic_mfg_aviatrix_default',
    'ic_mfg_t1_default',
    'ic_mfg_bgaming_default',
    'ic_mfg_bg_default',
    'ic_mfg_saba_default',
    'ic_mfg_kerala_default',
    'ic_mfg_omg_default',
    'ic_mfg_evonlc_default',
    'ic_mfg_evobtg_default',
    'ic_mfg_hacksaw_default',
    'ic_mfg_km_default',
    'ic_mfg_habanero_default',
    'ic_mfg_evoplay_default',
    'ic_mfg_winfinity_default',
    'ic_mfg_yellowbat_default',
    'ic_mfg_yeebet_default',
    'ic_mfg_atg_default',

    'ic_ranking_1',
    'ic_ranking_2',
    'ic_ranking_3',
  ],
};

//
export const LOCAL_POPUP_BANNER_MAPPING: Record<string, string[]> = {
  ['v6']: [
    'popup_deposit_wheel_surface',
    'popup_deposit_wheel_frame',
    'popup_deposit_wheel_button_disabled',
    'popup_first_recharge_vb',
    'popup_daily_loss_rebate',
    'popup_club',
    'popup_invite_wheel',
    'first_recharge_popup',
    'popup_surprise_reward',
    'popup_bet_rebate_1',
    'popup_bet_rebate_2',
    'popup_player_win_money',
    'popup_jackpot',
    'popup_low_balance_rescue_box_modal_bg',
  ],
};

// for [V] res
export const LOCAL_RESOURCES_MAPPING: Record<string, string[]> = {
  ['v6']: [
    // 舊名: amount_number_
    // 'number_imgs_v1_0',
    // 'number_imgs_v1_1',
    // 'number_imgs_v1_2',
    // 'number_imgs_v1_3',
    // 'number_imgs_v1_4',
    // 'number_imgs_v1_5',
    // 'number_imgs_v1_6',
    // 'number_imgs_v1_7',
    // 'number_imgs_v1_8',
    // 'number_imgs_v1_9',
    // 'number_imgs_v1_unit',
    // 'number_imgs_v1_comma',
    // 'number_imgs_v1_period',
    // 舊名: ranking_number_
    // 'number_imgs_v2_0',
    // 'number_imgs_v2_1',
    // 'number_imgs_v2_2',
    // 'number_imgs_v2_3',
    // 'number_imgs_v2_4',
    // 'number_imgs_v2_5',
    // 'number_imgs_v2_6',
    // 'number_imgs_v2_7',
    // 'number_imgs_v2_8',
    // 'number_imgs_v2_9',
    // 'number_imgs_v2_comma',
    // 'number_imgs_v2_period',
    // 舊名: animated_counter_
    // 'number_imgs_v3_0',
    // 'number_imgs_v3_1',
    // 'number_imgs_v3_2',
    // 'number_imgs_v3_3',
    // 'number_imgs_v3_4',
    // 'number_imgs_v3_5',
    // 'number_imgs_v3_6',
    // 'number_imgs_v3_7',
    // 'number_imgs_v3_8',
    // 'number_imgs_v3_9',
    // 'number_imgs_v3_plus',
    // 'number_imgs_v3_unit',
  ],
};

export const LOCAL_NUMBER_IMGS_MAPPING: Record<string, string[]> = {
  ['v6']: [
    // 舊名: amount_number_
    'number_imgs_v1_0',
    'number_imgs_v1_1',
    'number_imgs_v1_2',
    'number_imgs_v1_3',
    'number_imgs_v1_4',
    'number_imgs_v1_5',
    'number_imgs_v1_6',
    'number_imgs_v1_7',
    'number_imgs_v1_8',
    'number_imgs_v1_9',
    'number_imgs_v1_unit',
    'number_imgs_v1_comma',
    'number_imgs_v1_period',

    // 舊名: ranking_number_
    'number_imgs_v2_0',
    'number_imgs_v2_1',
    'number_imgs_v2_2',
    'number_imgs_v2_3',
    'number_imgs_v2_4',
    'number_imgs_v2_5',
    'number_imgs_v2_6',
    'number_imgs_v2_7',
    'number_imgs_v2_8',
    'number_imgs_v2_9',
    'number_imgs_v2_comma',
    'number_imgs_v2_period',

    // 舊名: animated_counter_
    'number_imgs_v3_0',
    'number_imgs_v3_1',
    'number_imgs_v3_2',
    'number_imgs_v3_3',
    'number_imgs_v3_4',
    'number_imgs_v3_5',
    'number_imgs_v3_6',
    'number_imgs_v3_7',
    'number_imgs_v3_8',
    'number_imgs_v3_9',
    'number_imgs_v3_plus',
    'number_imgs_v3_unit',
  ],
};
